// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc158/tasks/abc158_e
// 提交：https://atcoder.jp/contests/abc158/submit?taskScreenName=abc158_e
// 对拍：https://atcoder.jp/contests/abc158/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc158_e&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc158/submissions?f.Status=AC&f.Task=abc158_e&orderBy=source_length
func Test_e(t *testing.T) {
	testCases := [][2]string{
		{
			`4 3
3543`,
			`6`,
		},
		{
			`4 2
2020`,
			`10`,
		},
		{
			`20 11
33883322005544116655`,
			`68`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
