// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_b(t *testing.T) {
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithFile(t, doesValidArrayExist, "b.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
	if err := testutil.RunFuncWithRandomInput(t, doesValidArrayExist); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-345/problems/neighboring-bitwise-xor/
// https://leetcode.cn/problems/neighboring-bitwise-xor/
