// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2104/E
// https://codeforces.com/problemset/status/2104/problem/E?friends=on
func Test_cf2104E(t *testing.T) {
	testCases := [][2]string{
		{
			`7 3
abacaba
3
cc
bcb
b`,
			`0
1
2`,
		},
		{
			`5 1
aaaaa
6
a
aa
aaa
aaaa
aaaaa
aaaaaa`,
			`5
4
3
2
1
0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2104E)
}
