// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2110/C
// https://codeforces.com/problemset/status/2110/problem/C?friends=on
func Test_cf2110C(t *testing.T) {
	testCases := [][2]string{
		{
			`5
4
0 -1 -1 1
0 4
1 2
2 4
1 4
3
0 -1 -1
0 1
2 2
0 3
2
-1 -1
0 0
2 2
8
-1 -1 1 -1 -1 0 0 -1
0 0
0 1
0 2
0 2
1 3
0 4
2 5
4 5
1
0
1 1`,
			`0 1 1 1 
-1
-1
0 1 1 0 1 0 0 1 
-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2110C)
}
