// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2110/D
// https://codeforces.com/problemset/status/2110/problem/D?friends=on
func Test_cf2110D(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3 3
2 0 0
1 2 1
2 3 1
1 3 2
5 6
2 2 5 0 1
1 2 2
1 3 1
1 4 3
3 5 5
2 4 4
4 5 3
2 0
1 1
4 4
3 10 0 0
1 2 1
1 3 3
2 3 10
3 4 5`,
			`1
4
-1
10`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2110D)
}
