// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2113/F 2500
// https://codeforces.com/problemset/status/2113/problem/F?friends=on
func Test_cf2113F(t *testing.T) {
	testCases := [][2]string{
		{
			`3
5
1 2 4 4 4
1 3 3 5 2
7
2 2 4 4 5 5 5
1 3 3 2 1 6 6
7
12 3 3 4 5 6 4
1 2 13 8 10 13 7`,
			`9
1 3 4 5 2 
1 2 3 4 4 
12
2 3 4 2 1 5 6 
1 2 3 4 5 6 5 
14
12 3 13 8 10 6 4 
1 2 3 4 5 13 7`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2113F)
}
