// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2114/E
// https://codeforces.com/problemset/status/2114/problem/E?friends=on
func Test_cf2114E(t *testing.T) {
	testCases := [][2]string{
		{
			`2
5
4 5 2 6 7
1 2
3 2
4 3
5 1
6
1000000000 500500500 900900900 9 404 800800800
3 4
5 1
2 5
1 6
6 4`,
			`4 5 2 9 7 
1000000000 1500500096 1701701691 199199209 404 800800800`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2114E)
}
