// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2116/B 1300 2026.4.5
// https://codeforces.com/problemset/status/2116/problem/B?friends=on
func Test_cf2116B(t *testing.T) {
	testCases := [][2]string{
		{
			`3
3
0 2 1
1 2 0
5
0 1 2 3 4
4 3 2 1 0
10
5 8 9 3 4 0 2 7 1 6
9 5 1 4 0 3 2 8 7 6`,
			`3 6 8 
17 18 20 24 32 
544 768 1024 544 528 528 516 640 516 768`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2116B)
}
