// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2118/B 1200 2026.3.7
// https://codeforces.com/problemset/status/2118/problem/B?friends=on
func Test_cf2118B(t *testing.T) {
	testCases := [][2]string{
		{
			`2
3
4`,
			`4
2 1 3
2 2 3
3 1 2
3 2 3
5
2 1 4
3 1 3
3 2 4
4 3 4
4 1 2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2118B)
}
