// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2118/E 2400 2026.3.6
// https://codeforces.com/problemset/status/2118/problem/E?friends=on
func Test_cf2118E(t *testing.T) {
	testCases := [][2]string{
		{
			`3
3 3
1 1
1 5`,
			`2 1
2 3
2 2
1 1
3 2
3 3
3 1
1 3
1 2

1 1

1 2
1 4
1 5
1 1
1 3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2118E)
}
