// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2122/D 2400
// https://codeforces.com/problemset/status/2122/problem/D?friends=on
func Test_cf2122D(t *testing.T) {
	testCases := [][2]string{
		{
			`2
6 6
1 2
2 3
3 4
4 6
1 5
5 6
4 3
1 2
1 3
1 4`,
			`4 2
3 0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2122D)
}
