// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/2131/problem/F
// https://codeforces.com/problemset/status/2131/problem/F?friends=on
func Test_cf2131F(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2
11
00
2
01
01
4
1010
1101`,
			`5
4
24`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2131F)
}
