// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2143/D2 2200 2026.4.28
// https://codeforces.com/problemset/status/2143/problem/D2?friends=on
func Test_cf2143D2(t *testing.T) {
	testCases := [][2]string{
		{
			`4
4
4 2 3 1
7
7 6 1 2 3 3 2
5
1 1 1 1 1
11
7 2 1 9 7 3 4 1 3 5 3`,
			`13
73
32
619`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2143D2)
}
