// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2146/D1 1500
// https://codeforces.com/problemset/status/2146/problem/D1?friends=on
func Test_cf2146D1(t *testing.T) {
	testCases := [][2]string{
		{
			`3
0 3
0 9
0 15`,
			`12
3 2 1 0 
90
7 8 5 4 3 2 9 0 1 6
240
15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2146D1)
}
