// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2161/D 2100
// https://codeforces.com/problemset/status/2161/problem/D?friends=on
func Test_cf2161D(t *testing.T) {
	testCases := [][2]string{
		{
			`6
1
1
5
1 2 3 4 5
5
5 4 3 2 1
5
5 5 5 4 4
7
1 7 1 2 5 7 1
6
1 2 5 6 5 5`,
			`0
2
0
0
1
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2161D)
}
