// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2167/G
// https://codeforces.com/problemset/status/2167/problem/G?friends=on
func Test_cf2167G(t *testing.T) {
	testCases := [][2]string{
		{
			`10
1
10
5
4
1 2 2 3
5 6 7 8
4
4 3 2 1
1 1 1 1
3
3 1 2
100 1 1
5
5 5 5 5 5
10 1 10 1 10
5
1 3 2 2 4
100 1 1 1 100
6
10 9 8 7 6 5
1 100 1 100 1 100
5
100 1 100 100 100
1 100 1 1 1
4
2 1 2 1
5 4 3 2
7
1 5 3 4 2 6 7
10 1 10 1 10 1 10`,
			`0
0
3
2
0
1
203
1
6
11`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2167G)
}
