// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2171/E 2000
// https://codeforces.com/problemset/status/2171/problem/E?friends=on
func Test_cf2171E(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3
6
8
9`,
			`2 1 3
4 1 6 3 5 2
4 1 6 3 5 2 8 7
5 4 8 1 9 3 6 2 7`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2171E)
}
