// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2171/H
// https://codeforces.com/problemset/status/2171/problem/H?friends=on
func Test_cf2171H(t *testing.T) {
	testCases := [][2]string{
		{
			`6
4 20
6 6
6 216
3 500
2 8
5 29`,
			`7
5
19
13
3
9`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2171H)
}
