// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2175/B 1300 2026.5.3
// https://codeforces.com/problemset/status/2175/problem/B?friends=on
func Test_cf2175B(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3 1 3
4 1 3
8 2 4
4 3 4`,
			`9 8 1 
2 7 5 4 
9 1 9 8 10 5 4 9
85484 130377 6031 6031`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2175B)
}
