// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2181/G 2400 2026.4.17
// https://codeforces.com/problemset/status/2181/problem/G?friends=on
func Test_cf2181G(t *testing.T) {
	testCases := [][2]string{
		{
			`5
2
3 3
3
2 2 2
4
1 2 4 3
5
0 2 3 5 4
6
5 8 3 10 14 4`,
			`3
2
2
4
10`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2181G)
}
