// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2193/F 1600 2026.3.23
// https://codeforces.com/problemset/status/2193/problem/F?friends=on
func Test_cf2193F(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1 2 3 5 2
4
4
3 1 3 5 2
3 4 3
5 4 1
6 1 2 7 3
5 2 3 5 5 3
6 4 3 1 4 1
5 6 9 8 6
7 7 7 7 7
3 1 8 8 3`,
			`6
13
19
15`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2193F)
}
