// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2194/E 2000
// https://codeforces.com/problemset/status/2194/problem/E?friends=on
func Test_cf2194E(t *testing.T) {
	testCases := [][2]string{
		{
			`2
3 3
1 -2 3
4 -5 2
1 6 -1
2 4
-1 -1 -1 1
-1 -1 -1 -1`,
			`3
-5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2194E)
}
