// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/arc091/submit?taskScreenName=arc091_c
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`5 3 2`,
			`2 4 1 5 3`,
		},
		{
			`7 7 1`,
			`1 2 3 4 5 6 7`,
		},
		{
			`300000 300000 300000`,
			`-1`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/arc091/tasks/arc091_c
