// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_c(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, lexGreaterPermutation, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-472/problems/lexicographically-smallest-permutation-greater-than-target/
// https://leetcode.cn/problems/lexicographically-smallest-permutation-greater-than-target/
