// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`[0,1,2]`, 
			`0`,
		},
		{
			`[4,3,2,1]`, 
			`2`,
		},
		{
			`[1,2,3,4,5,6,7,8,9,0]`, 
			`-1`,
		},
		{
			`[2,1,3,5,2]`, 
			`1`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, smallestEqual, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-265/problems/smallest-index-with-equal-value/
