// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`"leet"`, `3`, `"e"`, `1`, 
			`"eet"`,
		},
		{
			`"leetcode"`, `4`, `"e"`, `2`, 
			`"ecde"`,
		},
		{
			`"bb"`, `2`, `"b"`, `2`, 
			`"bb"`,
		},
		{
			`"aaabbbcccddd"`, `3`, `"b"`, `2`,
			`"abb"`,
		},
		{
			`"facfffkfnffoppfffzfz"`, `9`, `"f"`, `9`,
			`"fffffffff"`,
		},
		{
			`"wuynymkihfdcbabefiiymnoyyytywzy"`, `16`, `"y"`, `4`,
			`"abefiimnoyytywzy"`,
		},
	}
	targetCaseNum := -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, smallestSubsequence, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-261/problems/smallest-k-length-subsequence-with-occurrences-of-a-letter/
