// Code generated by copypasta/template/acwing/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`6
10 7 1 9 10 15`,
			`26`,
		},
		{
			`1
400000`,
			`400000`,
		},
		{
			`7
8 9 26 11 12 29 14`,
			`55`,
		},
		
	}
	target := 0 // -1
	testutil.AssertEqualStringCase(t, testCases, target, run)
}
