// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P4310
func Test_p4310(t *testing.T) {
	testCases := [][2]string{
		{
			`3
1 2 3`,
			`2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p4310)
}
