// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [e]")
	examples := [][]string{
		{
			`[[1,1],[1,4],[3,2],[2,1]]`, `"LL"`,
			`[0,3,2,1]`,
		},
		{
			`[[1,3],[2,4],[3,3],[2,1]]`, `"LR"`,
			`[0,3,1,2]`,
		},
		{
			`[[10,2],[7,1],[2,6],[10,8],[5,1]]`, `"RLR"`,
			`[2,3,4,0,1]`,
		},
		{
			`[[69,86],[32,1],[100,7],[53,9],[91,64],[5,71],[34,90],[39,90],[53,65],[85,56]]`, `"LRRRRRRL"`,
			`[5,1,6,7,0,4,2,3,9,8]`,
		},
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, visitOrder, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/season/2020-spring/problems/you-le-yuan-de-mi-gong/
