// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/702/problem/C
// https://codeforces.com/problemset/status/702/problem/C
func Test_cf702C(t *testing.T) {
	testCases := [][2]string{
		{
			`3 2
-2 2 4
-3 0`,
			`4`,
		},
		{
			`5 3
1 5 10 14 17
4 11 15`,
			`3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf702C)
}
