// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/704/A 1600
// https://codeforces.com/problemset/status/704/problem/A?friends=on
func Test_cf704A(t *testing.T) {
	testCases := [][2]string{
		{
			`3 4
1 3
1 1
1 2
2 3`,
			`1
2
3
2`,
		},
		{
			`4 6
1 2
1 4
1 2
3 3
1 3
1 3`,
			`1
2
3
0
1
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf704A)
}
