// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/725/F 2900
// https://codeforces.com/problemset/status/725/problem/F?friends=on
func Test_cf725F(t *testing.T) {
	testCases := [][2]string{
		{
			`2
12 3 4 7
1 15 9 1`,
			`1`,
		},
		{
			`2
5 4 8 8
4 12 14 0`,
			`4`,
		},
		{
			`1
0 10 0 10`,
			`-10`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf725F)
}
