// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/744/C
// https://codeforces.com/problemset/status/744/problem/C?friends=on
func Test_cf744C(t *testing.T) {
	testCases := [][2]string{
		{
			`3
R 0 1
B 1 0
R 1 1`,
			`4`,
		},
		{
			`3
R 3 0
R 2 0
R 1 0`,
			`6`,
		},
		{
			`5
R 0 4
R 0 1
B 5 4
R 4 2
B 1 2`,
			`12`,
		},
		{
			`5
B 1 2
R 0 1
B 5 4
R 0 4
R 4 2
`,
			`12`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf744C)
}
