// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/750/E 2600
// https://codeforces.com/problemset/status/750/problem/E?friends=on
func Test_cf750E(t *testing.T) {
	testCases := [][2]string{
		{
			`8 3
20166766
1 8
1 7
2 8`,
			`4
3
-1`,
		},
		{
			`15 5
012016662091670
3 4
1 14
4 15
1 13
10 15`,
			`-1
2
1
-1
-1`,
		},
		{
			`4 2
1234
2 4
1 2`,
			`-1
-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf750E)
}
