// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/755/C
// https://codeforces.com/problemset/status/755/problem/C
func Test_cf755C(t *testing.T) {
	testCases := [][2]string{
		{
			`5
2 1 5 3 3`,
			`2`,
		},
		{
			`1
1`,
			`1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf755C)
}
