// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/776/B
// https://codeforces.com/problemset/status/776/problem/B
func Test_cf776B(t *testing.T) {
	testCases := [][2]string{
		{
			`3`,
			`2
1 1 2`,
		},
		{
			`4`,
			`2
2 1 1 2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf776B)
}
