// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/780/G 2700
// https://codeforces.com/problemset/status/780/problem/G?friends=on
func Test_cf780G(t *testing.T) {
	testCases := [][2]string{
		{
			`10 5 1
3 2 3 10`,
			`7`,
		},
		{
			`10 5 2
3 1 3 10
5 3 5 10`,
			`16`,
		},
		{
			`10 5 2
3 1 3 7
5 3 5 10`,
			`14`,
		},
		{
			`10 15 4
7 3 9 5
6 4 10 1
1 1 4 10
4 11 11 20`,
			`53`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf780G)
}
