// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_d(t *testing.T) {
	examples := [][]string{
		{
			`2`, `[3,3,3]`, 
			`4`,
		},
		{
			`2`, `[1,1,1,1]`, 
			`2`,
		},
		{
			`3`, `[10,10,3,5]`,
			`8`,
		},
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, maxRunTime, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-276/problems/maximum-running-time-of-n-computers/
