// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	exampleIns := [][]string{{`[[3,7,8],[9,11,13],[15,16,17]]`}, {`[[1,10,4,2],[9,3,8,7],[15,16,17,12]]`}, {`[[7,8],[1,2]]`}}
	exampleOuts := [][]string{{`[15]`}, {`[12]`}, {`[7]`}}
	// TODO: 测试参数的下界和上界！
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithCase(t, luckyNumbers, exampleIns, exampleOuts, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-180/problems/lucky-numbers-in-a-matrix/
