// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`"abc"`, `"bca"`, 
			`true`,
		},
		{
			`"a"`, `"aa"`, 
			`false`,
		},
		{
			`"cabbba"`, `"abbccc"`, 
			`true`,
		},
		{
			`"cabbba"`, `"aabbss"`, 
			`false`,
		},
		{
			`"uau"`, `"ssx"`,
			`false`,
		},
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, closeStrings, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-215/problems/determine-if-two-strings-are-close/
