// Code generated by copypasta/template/acwing/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`1`,
			`I hate it`,
		},
		{
			`2`,
			`I hate that I love it`,
		},
		{
			`3`,
			`I hate that I love that I hate it`,
		},
		{
			`4`,
			`I hate that I love that I hate that I love it`,
		},
		{
			`5`,
			`I hate that I love that I hate that I love that I hate it`,
		},
		
	}
	target := 0 // -1
	testutil.AssertEqualStringCase(t, testCases, target, run)
}
