// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/abc284/submit?taskScreenName=abc284_f
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`3
abcbac`,
			`abc
2`,
		},
		{
			`4
abababab`,
			`abab
1`,
		},
		{
			`3
agccga`,
			`cga
0`,
		},
		{
			`4
atcodeer`,
			`-1`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/abc284/tasks/abc284_f
