// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1017/E
// https://codeforces.com/problemset/status/1017/problem/E?friends=on
func Test_cf1017E(t *testing.T) {
	testCases := [][2]string{
		{
			`3 4
0 0
0 2
2 0
0 2
2 2
2 0
1 1`,
			`YES`,
		},
		{
			`3 4
0 0
0 2
2 0
0 2
2 2
2 0
0 0`,
			`NO`,
		},

		{
			`4 4
0 0
1 0
1 1
2 1
0 1
1 1
1 0
2 0`,
			`NO`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1017E)
}
