// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1025/F 2700
// https://codeforces.com/problemset/status/1025/problem/F?friends=on
func Test_cf1025F(t *testing.T) {
	testCases := [][2]string{
		{
			`6
1 1
2 2
4 6
4 5
7 2
5 3`,
			`6`,
		},
		{
			`7
0 -1000000000
-5 -5
5 -5
-5 0
5 0
-2 2
2 2`,
			`21`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1025F)
}
