// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1025/G 3200
// https://codeforces.com/problemset/status/1025/problem/G?friends=on
func Test_cf1025G(t *testing.T) {
	testCases := [][2]string{
		{
			`3
-1 -1 -1`,
			`3`,
		},
		{
			`2
2 -1`,
			`0`,
		},
		{
			`40
3 3 -1 -1 4 4 -1 -1 -1 -1 -1 10 10 10 10 10 10 4 20 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 3 3 3 3 3 3 3 3`,
			`755808950`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1025G)
}
