// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/1027/problem/C
// https://codeforces.com/problemset/status/1027/problem/C
func Test_cf1027C(t *testing.T) {
	testCases := [][2]string{
		{
			`3
4
7 2 2 7
8
2 8 1 4 8 2 1 5
5
5 5 5 5 5`,
			`2 7 7 2
2 2 1 1
5 5 5 5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1027C)
}
