// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1028/E
// https://codeforces.com/problemset/status/1028/problem/E?friends=on
func Test_cf1028E(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1 3 1 0`,
			`YES
1 3 5 2`,
		},
		{
			`2
4 4`,
			`NO`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1028E)
}
