// Generated by copypasta/template/generator_test.go
package main

import (
	"fmt"
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"io"
	"testing"
)

// https://codeforces.com/problemset/problem/1029/B
// https://codeforces.com/problemset/status/1029/problem/B
func Test_cf1029B(t *testing.T) {
	testCases := [][2]string{
		{
			`10
1 2 5 6 7 10 21 23 24 49`,
			`4`,
		},
		{
			`5
2 10 50 110 250`,
			`1`,
		},
		{
			`6
4 7 12 100 150 199`,
			`3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1029B)
}

// 读错题了
func TestCompare_cf1029B(_t *testing.T) {
	return
	testutil.DebugTLE = 0
	rg := testutil.NewRandGenerator()
	inputGenerator := func() string {
		//return ``
		rg.Clear()
		n := rg.Int(1, 3)
		rg.NewLine()
		rg.IntSliceOrdered(n, 1, 5,true,true)
		return rg.String()
	}

	// 暴力算法
	runBF := func(in io.Reader, out io.Writer) {
		var n,pre int
		fmt.Fscan(in, &n, &pre)
		max:=1
		cnt:=1
		for i:=1;i<n;i++{
			var cur int
			fmt.Fscan(in,&cur)
			if cur<=pre<<1{
				cnt++
				if max<cnt{
					max=cnt
				}
			}else{
				cnt=1
			}
			pre=cur
		}

		fmt.Fprint(out, max)
	}

	testutil.AssertEqualRunResultsInf(_t, inputGenerator, runBF, cf1029B)
}
