// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1043/F 2500
// https://codeforces.com/problemset/status/1043/problem/F?friends=on
func Test_cf1043F(t *testing.T) {
	testCases := [][2]string{
		{
			`3
10 6 15`,
			`3`,
		},
		{
			`3
2 4 6`,
			`-1`,
		},
		{
			`7
30 60 21 42 70 15 30`,
			`3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1043F)
}
