// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1066/B
// https://codeforces.com/problemset/status/1066/problem/B
func Test_cf1066B(t *testing.T) {
	testCases := [][2]string{
		{
			`6 2
0 1 1 0 0 1`,
			`3`,
		},
		{
			`5 3
1 0 0 0 1`,
			`2`,
		},
		{
			`5 10
0 0 0 0 0`,
			`-1`,
		},
		{
			`10 3
0 0 1 1 0 1 0 0 0 1`,
			`3`,
		},
		
		{
			`19 8
0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0`,
			`-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1066B)
}
