// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1073/D 1700
// https://codeforces.com/problemset/status/1073/problem/D?friends=on
func Test_cf1073D(t *testing.T) {
	testCases := [][2]string{
		{
			`3 38
5 2 5`,
			`10`,
		},
		{
			`5 21
2 4 100 2 6`,
			`6`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1073D)
}
