// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1080/E 2400
// https://codeforces.com/problemset/status/1080/problem/E?friends=on
func Test_cf1080E(t *testing.T) {
	testCases := [][2]string{
		{
			`1 3
aba`,
			`4`,
		},
		{
			`2 3
aca
aac`,
			`11`,
		},
		{
			`3 5
accac
aaaba
cccaa`,
			`43`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1080E)
}
