// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1080/F 2400
// https://codeforces.com/problemset/status/1080/problem/F?friends=on
func Test_cf1080F(t *testing.T) {
	testCases := [][2]string{
		{
			`5 5 9
3 6 3
1 3 1
2 4 2
1 2 3
4 6 5
2 5 3
7 9 4
2 3 1
4 10 4
1 2 2 3
1 2 2 4
1 3 1 5
2 3 3 6
2 4 2 9`,
			`no
yes
yes
no
yes`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1080F)
}
