// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1097/C
// https://codeforces.com/problemset/status/1097/problem/C
func Test_cf1097C(t *testing.T) {
	testCases := [][2]string{
		{
			`7
)())
)
((
((
(
)
)`,
			`2`,
		},
		{
			`4
(
((
(((
(())`,
			`0`,
		},
		{
			`2
(())
()`,
			`1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1097C)
}
