// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_d(t *testing.T) {
	examples := [][]string{
		{
			`"SSPPSPS"`, 
			`3`,
		},
		{
			`"PPSPSP"`, 
			`1`,
		},
		{
			`"S"`, 
			`0`,
		},
		{
			`"P"`,
			`0`,
		},
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, numberOfWays, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-70/problems/number-of-ways-to-divide-a-long-corridor/
