// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/practice2/tasks/practice2_e
// 提交：https://atcoder.jp/contests/practice2/submit?taskScreenName=practice2_e
// 对拍：https://atcoder.jp/contests/practice2/submissions?f.LanguageName=Go&f.Status=AC&f.Task=practice2_e&orderBy=source_length
// 最短：https://atcoder.jp/contests/practice2/submissions?f.Status=AC&f.Task=practice2_e&orderBy=source_length
func Test_e(t *testing.T) {
	testCases := [][2]string{
		{
			`3 1
5 3 2
1 4 8
7 6 9`,
			`19
X..
..X
.X.`,
		},
		{
			`3 2
10 10 1
10 10 1
1 1 10`,
			`50
XX.
XX.
..X`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
