// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_a(t *testing.T) {
	examples := [][]string{
		{
			`"K1:L2"`, 
			`["K1","K2","L1","L2"]`,
		},
		{
			`"A1:F1"`, 
			`["A1","B1","C1","D1","E1","F1"]`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, cellsInRange, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-283/problems/cells-in-a-range-on-an-excel-sheet/
