// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/agc021/tasks/agc021_d
// 提交：https://atcoder.jp/contests/agc021/submit?taskScreenName=agc021_d
// 对拍：https://atcoder.jp/contests/agc021/submissions?f.LanguageName=Go&f.Status=AC&f.Task=agc021_d&orderBy=source_length
// 最短：https://atcoder.jp/contests/agc021/submissions?f.Status=AC&f.Task=agc021_d&orderBy=source_length
func Test_d(t *testing.T) {
	testCases := [][2]string{
		{
			`abcabcabc
1`,
			`7`,
		},
		{
			`atcodergrandcontest
3`,
			`15`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
