// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	exampleIns := [][]string{{`"cdadabcc"`}, {`"abcd"`}, {`"ecbacba"`}, {`"leetcode"`}}
	exampleOuts := [][]string{{`"adbc"`}, {`"abcd"`}, {`"eacb"`}, {`"letcod"`}}
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	if err := testutil.RunLeetCodeFunc(t, smallestSubsequence, exampleIns, exampleOuts); err != nil {
		t.Fatal(err)
	}
}
