// Code generated by copypasta/template/nowcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`8`,`3`,`3`,
			`-1`,
		},
		{
			`3`,`4`,`2`,
			`1`,
		},
		{
			`6`,`3`,`2`,
			`1`,
		},
		{
			`6`,`3`,`5`,
			`-1`,
		},
		// TODO 测试参数的下界和上界
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, Gameresults, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://ac.nowcoder.com/acm/contest/9753/b
