// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`"1&(0|1)"`,
			`1`,
		},
		{
			`"(0&0)&(0&0&0)"`,
			`3`,
		},
		{
			`"(0|(1|0&1))"`,
			`1`,
		},
		// TODO 测试入参最小的情况
		{
			`"1&(0|1)"`,
			`1`,
		},
		{
			`"1|1|(0&0)&1"`,
			`1`,
		},
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, minOperationsToFlip, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode-cn.com/contest/biweekly-contest-54/problems/minimum-cost-to-change-the-final-value-of-expression/
