// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/arc146/tasks/arc146_b 1335
// 提交：https://atcoder.jp/contests/arc146/submit?taskScreenName=arc146_b
// 对拍：https://atcoder.jp/contests/arc146/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc146_b&orderBy=source_length
// 最短：https://atcoder.jp/contests/arc146/submissions?f.Status=AC&f.Task=arc146_b&orderBy=source_length
func Test_b(t *testing.T) {
	testCases := [][2]string{
		{
			`4 8 2
1 2 4 8`,
			`10`,
		},
		{
			`5 345 3
111 192 421 390 229`,
			`461`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
