// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/abc178/submit?taskScreenName=abc178_f
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`6
1 1 1 2 2 3
1 1 1 2 2 3`,
			`Yes
2 2 3 1 1 1`,
		},
		{
			`3
1 1 2
1 1 3`,
			`No`,
		},
		{
			`4
1 1 2 3
1 2 3 3`,
			`Yes
3 3 1 2`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/abc178/tasks/abc178_f
