// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/B3717
func Test_b3717(t *testing.T) {
	testCases := [][2]string{
		{
			`3 5
3 3
4 2
5 3`,
			`13`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, b3717)
}
