// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P1314
func Test_p1314(t *testing.T) {
	testCases := [][2]string{
		{
			`5 3 15 
1 5 
2 5 
3 5 
4 5 
5 5 
1 5 
2 4 
3 3`,
			`10`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p1314)
}
