// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P1939
func Test_p1939(t *testing.T) {
	testCases := [][2]string{
		{
			`3
6
8
10`,
			`4
9
19`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p1939)
}
