// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P1966
func Test_p1966(t *testing.T) {
	testCases := [][2]string{
		{
			`4
2 3 1 4
3 2 1 4`,
			`1`,
		},
		{
			`4
1 3 4 2
1 7 2 4`,
			`2`,
		},
		{
			`50
41 29 19 46 13 28 47 17 45 4 34 14 37 7 30 24 27 9 11 15 50 8 39 32 3 42 10 16 31 6 1 43 21 36 2 23 26 49 33 12 40 35 22 48 5 25 20 18 44 38 
43 13 32 28 41 3 8 20 37 22 40 34 33 24 47 21 39 14 17 6 18 50 19 26 45 44 9 30 42 1 35 49 15 5 23 16 29 27 36 38 2 25 46 48 7 31 4 11 10 12`,
			`540`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p1966)
}
