// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P2572
func Test_p2572(t *testing.T) {
	testCases := [][2]string{
		{
			`10 10
0 0 0 1 1 0 1 0 1 1
1 0 2
3 0 5
2 2 2
4 0 4
0 3 6
2 3 7
4 2 8
1 0 5
0 5 6
3 3 9`,
			`5
2
6
5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p2572)
}
