// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P3177
func Test_p3177(t *testing.T) {
	testCases := [][2]string{
		{
			`3 1
1 2 1
1 3 2`,
			`3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p3177)
}
