// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P3957
func Test_p3957(t *testing.T) {
	testCases := [][2]string{
		{
			`7 4 10
2 6
5 -3
10 3
11 -3
13 1
17 6
20 2`,
			`2`,
		},
		{
			`7 4 20
2 6
5 -3
10 3
11 -3
13 1
17 6
20 2`,
			`-1`,
		},
		{
			`10 72 112
16 18
18 -5
45 32
95 43
126 46
168 42
214 14
256 4
302 6
347 0`,
			`27`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p3957)
}
