// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P4071
func Test_p4071(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1 0
1 1
5 2
100 50
10000 5000`,
			`0
1
20
578028887
60695423`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p4071)
}
