// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P4513
func Test_p4513(t *testing.T) {
	testCases := [][2]string{
		{
			`5 3
1
2
-3
4
5
1 2 3
2 2 -1
1 2 3`,
			`2
-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p4513)
}
