// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc372/tasks/abc372_e
// 提交：https://atcoder.jp/contests/abc372/submit?taskScreenName=abc372_e
// 对拍：https://atcoder.jp/contests/abc372/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc372_e&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc372/submissions?f.Status=AC&f.Task=abc372_e&orderBy=source_length
func Test_e(t *testing.T) {
	testCases := [][2]string{
		{
			`4 10
1 1 2
2 1 1
2 1 2
2 1 3
1 1 3
1 2 3
1 3 4
2 1 1
2 1 3
2 1 5`,
			`2
1
-1
4
2
-1`,
		},
		{
			`6 20
1 3 4
1 3 5
2 1 1
2 3 1
1 1 5
2 6 9
2 1 3
2 6 1
1 4 6
2 2 1
2 6 2
2 4 7
1 1 4
2 6 2
2 3 4
1 2 5
2 4 1
1 1 6
2 3 3
2 1 3`,
			`1
5
-1
3
6
2
5
-1
5
3
6
4
4`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
