// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2008/F
// https://codeforces.com/problemset/status/2008/problem/F?friends=on
func Test_cf2008F(t *testing.T) {
	testCases := [][2]string{
		{
			`3
3
3 2 3
4
2 2 2 4
5
1 2 3 4 5`,
			`7
6
500000012`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2008F)
}
