// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/2009/problem/E
// https://codeforces.com/problemset/status/2009/problem/E?friends=on
func Test_cf2009E(t *testing.T) {
	testCases := [][2]string{
		{
			`4
2 2
7 2
5 3
1000000000 1000000000`,
			`1
5
1
347369930`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2009E)
}
