// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2021/B
// https://codeforces.com/problemset/status/2021/problem/B?friends=on
func Test_cf2021B(t *testing.T) {
	testCases := [][2]string{
		{
			`3
6 3
0 3 2 1 5 2
6 2
1 3 4 1 0 2
4 5
2 5 10 3`,
			`4
6
0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2021B)
}
