// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2031/C 1300 2026.3.12
// https://codeforces.com/problemset/status/2031/problem/C?friends=on
func Test_cf2031C(t *testing.T) {
	testCases := [][2]string{
		{
			`2
3
12`,
			`-1
1 2 3 6 10 2 7 6 10 1 7 3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2031C)
}
