// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2038/I 2500
// https://codeforces.com/problemset/status/2038/problem/I?friends=on
func Test_cf2038I(t *testing.T) {
	testCases := [][2]string{
		{
			`3 5
10010
01100
10101`,
			`3 2 3 1 3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2038I)
}
