// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2039/C2
// https://codeforces.com/problemset/status/2039/problem/C2?friends=on
func Test_cf2039C2(t *testing.T) {
	testCases := [][2]string{
		{
			`5
7 10
2 3
6 4
1 6
4 1`,
			`3
2
2
6
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2039C2)
}
