// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2042/D
// https://codeforces.com/problemset/status/2042/problem/D?friends=on
func Test_cf2042D(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3
3 8
2 5
4 5
2
42 42
1 1000000000
3
42 42
1 1000000000
42 42
6
1 10
3 10
3 7
5 7
4 4
1 2`,
			`0
0
1
999999999
0
0
0
0
0
2
3
2
4
8`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2042D)
}
