// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/2045/problem/B
// https://codeforces.com/problemset/status/2045/problem/B?friends=on
func Test_cf2045B(t *testing.T) {
	testCases := [][2]string{
		{
			`64 35 3`,
			`60`,
		},
		{
			`2024 2023 1273`,
			`1273`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2045B)
}
