// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2045/H
// https://codeforces.com/problemset/status/2045/problem/H?friends=on
func Test_cf2045H(t *testing.T) {
	testCases := [][2]string{
		{
			`ABACUS`,
			`4
A
BA
C
US`,
		},
		{
			`AAAAAA`,
			`3
A
AA
AAA`,
		},
		{
			`EDCBA`,
			`1
EDCBA`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2045H)
}
