// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2048/G 2800
// https://codeforces.com/problemset/status/2048/problem/G?friends=on
func Test_cf2048G(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2 2 2
2 3 4
11 45 14`,
			`14
2824
883799966`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2048G)
}
