// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2051/E
// https://codeforces.com/problemset/status/2051/problem/E?friends=on
func Test_cf2051E(t *testing.T) {
	testCases := [][2]string{
		{
			`5
2 0
2 1
3 4
1 1
2
5
3 3
1 5 2
3 6 4
4 3
2 3 2 8
3 7 3 9
3 1
2 9 5
12 14 9`,
			`2
5
9
14
15`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2051E)
}
