// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/2051/problem/F
// https://codeforces.com/problemset/status/2051/problem/F?friends=on
func Test_cf2051F(t *testing.T) {
	testCases := [][2]string{
		{
			`5
6 5 3
1 2 3
2 1 4
2 1 1 2
5 3 1
3
3 2 4
2 1 1 1
18 15 4
13 15 1 16`,
			`2 3 5 
2 2 2 2 
2 
2 3 3 3 
2 4 6 8`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2051F)
}
