// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2053/C
// https://codeforces.com/problemset/status/2053/problem/C?friends=on
func Test_cf2053C(t *testing.T) {
	testCases := [][2]string{
		{
			`6
7 2
11 3
55 13
5801 6
8919 64
8765432 1`,
			`12
18
196
1975581
958900
38416403456028`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2053C)
}
