// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2057/C
// https://codeforces.com/problemset/status/2057/problem/C?friends=on
func Test_cf2057C(t *testing.T) {
	testCases := [][2]string{
		{
			`8
0 2
0 8
1 3
6 22
128 137
69 98
115 127
0 1073741823`,
			`1 2 0
8 7 1
2 1 3
7 16 11
134 132 137
98 85 76
123 121 118
965321865 375544086 12551794`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2057C)
}
