// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2061/C
// https://codeforces.com/problemset/status/2061/problem/C?friends=on
func Test_cf2061C(t *testing.T) {
	testCases := [][2]string{
		{
			`8
3
0 1 2
5
0 0 0 0 0
5
0 0 1 1 2
5
0 1 2 3 4
5
0 0 1 1 1
5
5 1 5 2 5
1
0
4
2 3 1 1`,
			`1
2
3
0
4
1
2
0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2061C)
}
