// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2063/F2 2700
// https://codeforces.com/problemset/status/2063/problem/F2?friends=on
func Test_cf2063F2(t *testing.T) {
	testCases := [][2]string{
		{
			`3
3
2 5
1 6
3 4
4
1 6
7 8
2 3
4 5
6
2 3
1 6
7 8
9 12
10 11
4 5`,
			`5 1 1 1
14 2 2 1 1
132 42 5 2 1 1 1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2063F2)
}
