// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2064/D
// https://codeforces.com/problemset/status/2064/problem/D?friends=on
func Test_cf2064D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
1 1
5
6
4 4
1 5 4 11
8
13
16
15
10 9
10 4 3 9 7 4 6 1 9 4
2
6
5
6
9
8
6
2
7`,
			`1
0 2 4 2
0 1 1 1 3 3 1 0 1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2064D)
}
