// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2069/D
// https://codeforces.com/problemset/status/2069/problem/D?friends=on
func Test_cf2069D(t *testing.T) {
	testCases := [][2]string{
		{
			`4
baba
cc
ddaa
acbacddacbca`,
			`2
0
3
2`,
		},
		{
			`1
ktffetfekktttteeekffkekkttfttfeftefftk`,
			`12`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2069D)
}
