// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2070/D 1600
// https://codeforces.com/problemset/status/2070/problem/D?friends=on
func Test_cf2070D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
4
1 2 1
3
1 2
7
1 2 2 1 4 5`,
			`4
2
8`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2070D)
}
