// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/2075/problem/D
// https://codeforces.com/problemset/status/2075/problem/D?friends=on
func Test_cf2075D(t *testing.T) {
	testCases := [][2]string{
		{
			`5
0 1
6 2
3 3
13 37
4238659325782394 12983091057341925`,
			`2
6
0
26
32764`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2075D)
}
