// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2085/F2 2900 2026.4.4
// https://codeforces.com/problemset/status/2085/problem/F2?friends=on
func Test_cf2085F2(t *testing.T) {
	testCases := [][2]string{
		{
			`6
3 2
1 2 1
7 3
2 1 1 3 1 1 2
6 3
1 1 2 2 2 3
6 3
1 2 2 2 2 3
10 5
5 1 3 1 1 2 2 4 1 3
9 4
1 2 3 3 3 3 3 2 4`,
			`0
1
2
3
4
5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2085F2)
}
