// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2094/H
// https://codeforces.com/problemset/status/2094/problem/H?friends=on
func Test_cf2094H(t *testing.T) {
	testCases := [][2]string{
		{
			`2
5 3
2 3 5 7 11
2 1 5
2 2 4
2310 1 5
4 3
18 12 8 9
216 1 2
48 2 4
82944 1 4`,
			`5
6
1629
13
12
520`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2094H)
}
