// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2097/C 2400 2026.6.11
// https://codeforces.com/problemset/status/2097/problem/C?friends=on
func Test_cf2097C(t *testing.T) {
	testCases := [][2]string{
		{
			`6
6 2 2 5 2
6 2 2 20 8
4 1 2 1 1
4 1 1 1 2
4 1 1 2 1
6 2 3 2 3`,
			`2
2
-1
-1
-1
5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2097C)
}
