// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc368/tasks/abc368_f
// 提交：https://atcoder.jp/contests/abc368/submit?taskScreenName=abc368_f
// 对拍：https://atcoder.jp/contests/abc368/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc368_f&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc368/submissions?f.Status=AC&f.Task=abc368_f&orderBy=source_length
func Test_f(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2 3 4`,
			`Anna`,
		},
		{
			`4
2 3 4 6`,
			`Bruno`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
