// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc387/tasks/abc387_c
// 提交：https://atcoder.jp/contests/abc387/submit?taskScreenName=abc387_c
// 对拍：https://atcoder.jp/contests/abc387/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc387_c&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc387/submissions?f.Status=AC&f.Task=abc387_c&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`97 210`,
			`6`,
		},
		{
			`1000 9999`,
			`2025`,
		},
		{
			`252509054433933519 760713016476190692`,
			`221852052834757`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
