// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`"leEeetcode"`, 
			`"leetcode"`,
		},
		{
			`"abBAcC"`, 
			`""`,
		},
		{
			`"s"`, 
			`"s"`,
		},
		// TODO 测试参数的下界和上界
		{
			`"Pp"`,
			`""`,
		},
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, makeGood, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-201/problems/make-the-string-great/
