// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P10725
func Test_p10725(t *testing.T) {
	testCases := [][2]string{
		{
			`5
0 1 0 1 0
1 2
1 3
3 4
3 5`,
			`3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p10725)
}
