// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P10949
func Test_p10949(t *testing.T) {
	testCases := [][2]string{
		{
			`3 3
50 -20 -30
0 1 10
1 2 20
0 2 100`,
			`30`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p10949)
}
