// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc094/tasks/arc095_b
// 提交：https://atcoder.jp/contests/arc095/submit?taskScreenName=arc095_b
// 对拍：https://atcoder.jp/contests/arc095/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc095_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`5
6 9 4 2 11`,
			`11 6`,
		},
		{
			`2
100 0`,
			`100 0`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
