// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc396/tasks/abc396_g
// 提交：https://atcoder.jp/contests/abc396/submit?taskScreenName=abc396_g
// 对拍：https://atcoder.jp/contests/abc396/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc396_g&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc396/submissions?f.Status=AC&f.Task=abc396_g&orderBy=source_length
func Test_g(t *testing.T) {
	testCases := [][2]string{
		{
			`3 3
100
010
110`,
			`2`,
		},
		{
			`3 4
1111
1111
1111`,
			`0`,
		},
		{
			`10 5
10000
00111
11000
01000
10110
01110
10101
00100
00100
10001`,
			`13`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
