// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/601/E 2800
// https://codeforces.com/problemset/status/601/problem/E?friends=on
func Test_cf601E(t *testing.T) {
	testCases := [][2]string{
		{
			`3 10
30 4
60 6
5 1
9
3
1 42 5
1 20 3
3
2 2
2 4
3
1 40 6
3`,
			`556674384
168191145
947033915
181541912`,
		},
		{
			`3 1000
100 42
100 47
400 15
4
2 2
2 1
2 3
3`,
			`0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf601E)
}
