// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/628/F 2500
// https://codeforces.com/problemset/status/628/problem/F?friends=on
func Test_cf628F(t *testing.T) {
	testCases := [][2]string{
		{
			`10 20 1
10 10`,
			`fair`,
		},
		{
			`10 20 3
15 10
5 0
10 5`,
			`fair`,
		},
		{
			`10 20 2
15 3
20 10`,
			`unfair`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf628F)
}
