// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/639/D 2400 2026.6.5
// https://codeforces.com/problemset/status/639/problem/D?friends=on
func Test_cf639D(t *testing.T) {
	testCases := [][2]string{
		{
			`4 3 100 30
12 2 6 1`,
			`220`,
		},
		{
			`4 3 30 100
12 2 6 1`,
			`190`,
		},
		{
			`6 2 987 789
-8 42 -4 -65 -8 -8`,
			`0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf639D)
}
