// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/645/D
// https://codeforces.com/problemset/status/645/problem/D?friends=on
func Test_cf645D(t *testing.T) {
	testCases := [][2]string{
		{
			`4 5
2 1
1 3
2 3
4 2
4 3`,
			`4`,
		},
		{
			`3 2
1 2
3 2`,
			`-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf645D)
}
