// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/670/problem/D2
// https://codeforces.com/problemset/status/670/problem/D2
func TestCF670D2(t *testing.T) {
	testCases := [][2]string{
		{
			`1 1000000000
1
1000000000`,
			`2000000000`,
		},
		{
			`10 1
1000000000 1000000000 1000000000 1000000000 1000000000 1000000000 1000000000 1000000000 1000000000 1000000000
1 1 1 1 1 1 1 1 1 1`,
			`0`,
		},
		{
			`3 1
2 1 4
11 3 16`,
			`4`,
		},
		{
			`4 3
4 3 5 6
11 12 14 20`,
			`3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, CF670D2)
}
