// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/676/E 2400
// https://codeforces.com/problemset/status/676/problem/E?friends=on
func Test_cf676E(t *testing.T) {
	testCases := [][2]string{
		{
			`1 2
-1
?`,
			`Yes`,
		},
		{
			`2 100
-10000
0
1`,
			`Yes`,
		},
		{
			`4 5
?
1
?
1
?`,
			`No`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf676E)
}
