// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/690/A3 2400
// https://codeforces.com/problemset/status/690/problem/A3?friends=on
func Test_cf690A3(t *testing.T) {
	testCases := [][2]string{
		{
			`4
2 1
1
2 2
1
2 1
2
2 2
2`,
			`1
2
2
1`,
		},
		{
			`2
5 2
2 2 2 2
6 4
3 2 6 1 2`,
			`5
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf690A3)
}
