// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/123/E 2500
// https://codeforces.com/problemset/status/123/problem/E?friends=on
func Test_cf123E(t *testing.T) {
	testCases := [][2]string{
		{
			`2
1 2
0 1
1 0`,
			`1.00000000000000000000`,
		},
		{
			`3
1 2
1 3
1 0
0 2
0 3`,
			`2.00000000000000000000`,
		},
		{
			`7
1 2
1 3
2 4
2 5
3 6
3 7
1 1
1 1
1 1
1 1
1 1
1 1
1 1`,
			`4.04081632653`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf123E)
}
