// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/163/E
// https://codeforces.com/problemset/status/163/problem/E
func TestCF163E(t *testing.T) {
	testCases := [][2]string{
		{
			`7 3
a
aa
ab
?aaab
-2
?aaab
-3
?aaab
+2
?aabbaa`,
			`6
4
3
6`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, CF163E)
}
