// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/180/C
// https://codeforces.com/problemset/status/180/problem/C
func Test_cf180C(t *testing.T) {
	testCases := [][2]string{
		{
			`PRuvetSTAaYA`,
			`5`,
		},
		{
			`OYPROSTIYAOPECHATALSYAPRIVETSTASYA`,
			`0`,
		},
		{
			`helloworld`,
			`0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf180C)
}
