// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	exampleIns := [][]string{{`6`, `[2,10,3,1,5,8]`, `[5,4,3,9,7,2]`, `2`}, {`6`, `[2,10,3,1,5,8]`, `[5,4,3,9,7,2]`, `3`}, {`6`, `[2,10,3,1,5,8]`, `[5,4,3,9,7,2]`, `4`}}
	exampleOuts := [][]string{{`60`}, {`68`}, {`72`}}
	// TODO: 测试参数的下界和上界！
	// custom test cases or WA cases.
	exampleIns = append(exampleIns, []string{`3`,`[2,8,2]`,`[2,7,1]`,`2`})
	exampleOuts = append(exampleOuts, []string{`56`})
	targetCaseNum := 2
	if err := testutil.RunLeetCodeFuncWithCase(t, maxPerformance, exampleIns, exampleOuts, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-180/problems/maximum-performance-of-a-team/
//3
//[2,8,2]
//[2,7,1]
//2

// 56