// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`[2,3,-1,8,4]`, 
			`3`,
		},
		{
			`[1,-1,4]`, 
			`2`,
		},
		{
			`[2,5]`, 
			`-1`,
		},
		{
			`[1]`, 
			`0`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, findMiddleIndex, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-60/problems/find-the-middle-index-in-array/
