// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/514/B
// https://codeforces.com/problemset/status/514/problem/B?friends=on
func Test_cf514B(t *testing.T) {
	testCases := [][2]string{
		{
			`4 0 0
1 1
2 2
2 0
-1 -1`,
			`2`,
		},
		{
			`2 1 2
1 1
1 0`,
			`1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf514B)
}
