// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/525/D
// https://codeforces.com/problemset/status/525/problem/D?friends=on
func Test_cf525D(t *testing.T) {
	testCases := [][2]string{
		{
			`5 5
.*.*.
*****
.*.*.
*****
.*.*.`,
			`.*.*.
*****
.*.*.
*****
.*.*.`,
		},
		{
			`6 7
***.*.*
..*.*.*
*.*.*.*
*.*.*.*
..*...*
*******`,
			`***...*
..*...*
..*...*
..*...*
..*...*
*******`,
		},
		{
			`4 5
.....
.....
..***
..*..`,
			`.....
.....
.....
.....`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf525D)
}
