// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/525/E
// https://codeforces.com/problemset/status/525/problem/E?friends=on
func Test_cf525E(t *testing.T) {
	testCases := [][2]string{
		{
			`2 2 30
4 3`,
			`1`,
		},
		{
			`2 2 7
4 3`,
			`1`,
		},
		{
			`3 1 1
1 1 1`,
			`6`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf525E)
}
