// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/534/C
// https://codeforces.com/problemset/status/534/problem/C
func TestCF534C(t *testing.T) {
	testCases := [][2]string{
		{
			`2 8
4 4`,
			`3 3`,
		},
		{
			`1 3
5`,
			`4`,
		},
		{
			`2 3
2 3`,
			`0 1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, CF534C)
}
