// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/547/D
// https://codeforces.com/problemset/status/547/problem/D
func Test_cf547D(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1 1
1 2
2 1
2 2`,
			`brrb`,
		},
		{
			`3
1 1
1 2
2 1`,
			`brr`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf547D)
}
