// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/593/D 2400
// https://codeforces.com/problemset/status/593/problem/D?friends=on
func Test_cf593D(t *testing.T) {
	testCases := [][2]string{
		{
			`6 6
1 2 1
1 3 7
1 4 4
2 5 5
2 6 2
1 4 6 17
2 3 2
1 4 6 17
1 5 5 20
2 4 1
1 5 1 3`,
			`2
4
20
3`,
		},
		{
			`5 4
1 2 7
1 3 3
3 4 2
3 5 5
1 4 2 100
1 5 4 1
2 2 2
1 1 3 4`,
			`2
0
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf593D)
}
