// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P9242
func Test_p9242(t *testing.T) {
	testCases := [][2]string{
		{
			`5
11 121 22 12 2023`,
			`1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p9242)
}
