// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/abc184/submit?taskScreenName=abc184_b
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`3 0
xox`,
			`0`,
		},
		{
			`20 199999
oooooooooxoooooooooo`,
			`200017`,
		},
		{
			`20 10
xxxxxxxxxxxxxxxxxxxx`,
			`0`,
		},
		// TODO 测试参数的下界和上界
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/abc184/tasks/abc184_b
