// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	testutil2 "github.com/EndlessCheng/codeforces-go/main/testutil"
	"math"
	"slices"
	"testing"
)

func Test_c(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, maxSubarraySum, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-508/problems/maximum-subarray-sum-after-multiplier/
// https://leetcode.cn/problems/maximum-subarray-sum-after-multiplier/

func TestCompareInf(_t *testing.T) {
	return
	testutil.DebugTLE = 0
	rg := testutil2.NewRandGenerator()
	inputGenerator := func() (a []int, k int) {
		//return
		rg.Clear()
		n := rg.Int(1, 20)
		a = rg.IntSlice(n, -20, 20)
		k = rg.Int(1, 20)
		return
	}

	ff := func(a []int) int64 {
		res, f := math.MinInt, 0
		for _, v := range a {
			f = max(f, 0) + v
			res = max(res, f)
		}
		return int64(res)
	}

	runAC := func(a []int, k int) (ans int64) {
		ans = -1e18
		for l := range a {
			b := slices.Clone(a)
			for r := l; r < len(b); r++ {
				b[r] *= k
				ans = max(ans, ff(b))
			}
			b = slices.Clone(a)
			for r := l; r < len(b); r++ {
				b[r] /= k
				ans = max(ans, ff(b))
			}
		}
		return
	}

	testutil.CompareInf(_t, inputGenerator, runAC, maxSubarraySum)
}
