// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`[2,3]`, `1`, 
			`"HHHVV"`,
		},
		{
			`[2,3]`, `2`, 
			`"HHVHV"`,
		},
		{
			`[2,3]`, `3`, 
			`"HHVVH"`,
		},
		
	}
	targetCaseNum := 2
	if err := testutil.RunLeetCodeFuncWithExamples(t, kthSmallestPath, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-213/problems/kth-smallest-instructions/
