// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	exampleIns := [][]string{{`9669`}, {`9996`}, {`9999`}}
	exampleOuts := [][]string{{`9969`}, {`9999`}, {`9999`}}
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	if err := testutil.RunLeetCodeFunc(t, maximum69Number, exampleIns, exampleOuts); err != nil {
		t.Fatal(err)
	}
}
