// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_c(t *testing.T) {
	examples := [][]string{
		{
			`12`, 
			`[2,4,6]`,
		},
		{
			`7`, 
			`[]`,
		},
		{
			`28`, 
			`[6,8,2,12]`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, maximumEvenSplit, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-72/problems/maximum-split-of-positive-even-integers/
