// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[3,5,1,2,4]`, `1`, 
			`4`,
		},
		{
			`[3,1,5,4,2]`, `2`, 
			`-1`,
		},
		{
			`[1]`, `1`, 
			`1`,
		},
		{
			`[2,1]`, `2`, 
			`2`,
		},
		// TODO 测试参数的下界和上界
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, findLatestStep, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-203/problems/find-latest-group-of-size-m/
