// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_b(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, reverseWords, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-480/problems/reverse-words-with-same-vowel-count/
// https://leetcode.cn/problems/reverse-words-with-same-vowel-count/
