// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://oj.niumacode.com/problem/P1499
func Test_p1499(t *testing.T) {
	testCases := [][2]string{
		{
			`4 4
1 2 1
1 3 2
1 4 1
2 1
4 3
1 4
2 4`,
			`3
3
3
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p1499)
}
