// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	testutil2 "github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

func Test_c(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, maxGCDScore, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/biweekly-contest-158/problems/maximize-subarray-gcd-score/
// https://leetcode.cn/problems/maximize-subarray-gcd-score/

func TestCompareInf(_t *testing.T) {
	//return
	testutil.DebugTLE = 0
	rg := testutil2.NewRandGenerator()
	inputGenerator := func() (a []int,k int) {
		//return
		rg.Clear()
		n := rg.Int(1, 30)
		a = rg.IntSlice(n, 1, 24)
		k = rg.Int(1, n)
		return
	}

	testutil.CompareInf(_t, inputGenerator, maxGCDScore1, maxGCDScore)
}
