// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/abc240/submit?taskScreenName=abc240_c
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`2 10
3 6
4 5`,
			`Yes`,
		},
		{
			`2 10
10 100
10 100`,
			`No`,
		},
		{
			`4 12
1 8
5 7
3 4
2 6`,
			`Yes`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/abc240/tasks/abc240_c
