// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`"1 box has 3 blue 4 red 6 green and 12 yellow marbles"`, 
			`true`,
		},
		{
			`"hello world 5 x 5"`, 
			`false`,
		},
		{
			`"sunset is at 7 51 pm overnight lows will be in the low 50 and 60 s"`, 
			`false`,
		},
		{
			`"4 5 11 26"`, 
			`true`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, areNumbersAscending, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-263/problems/check-if-numbers-are-ascending-in-a-sentence/
