// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_c(t *testing.T) {
	examples := [][]string{
		{
			`9`, `[1,1,0,1,0,0,2,1,0,1,2,0]`, 
			`[0,0,0,0,1,1,0,0,1,2,3,1]`,
		},
		{
			`3`, `[0,0,1,0,0,0,0,0,0,0,0,2]`, 
			`[0,0,0,0,0,0,0,0,1,1,1,0]`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, maximumBobPoints, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-285/problems/maximum-points-in-an-archery-competition/
