// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`3`, `[[1,2],[1,3],[1,8],[2,6],[3,1],[3,10]]`, 
			`4`,
		},
		{
			`2`, `[[2,1],[1,8],[2,6]]`, 
			`2`,
		},
		{
			`4`, `[[4,3],[1,4],[4,6],[1,7]]`, 
			`4`,
		},
		
	}
	targetCaseNum := 2
	if err := testutil.RunLeetCodeFuncWithExamples(t, maxNumberOfFamilies, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-22/problems/cinema-seat-allocation/
