// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/arc103/submit?taskScreenName=arc103_c
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`1111`,
			`-1`,
		},
		{
			`1110`,
			`1 2
2 3
3 4`,
		},
		{
			`1010`,
			`1 2
1 3
1 4`,
		},
		// TODO 测试参数的下界和上界
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/arc103/tasks/arc103_c
