// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`"cba"`, 
			`5`,
		},
		{
			`"aabaa"`, 
			`2`,
		},
		{
			`"cdbea"`, 
			`63`,
		},
		{
			`"leetcodeleetcodeleetcode"`, 
			`982157772`,
		},
		// TODO 测试入参最小的情况
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, makeStringSorted, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-50/problems/minimum-number-of-operations-to-make-string-sorted/
