// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`[5,2,6,3,9,1,7,3,8,4]`, 
			`[5,6,2,3,9,1,4,8,3,7]`,
		},
		{
			`[1,1,0,6]`, 
			`[1,0,1,6]`,
		},
		{
			`[2,1]`, 
			`[2,1]`,
		},
		{
			`[8]`, 
			`[8]`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, reverseEvenLengthGroups, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-267/problems/reverse-nodes-in-even-length-groups/
