// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	sampleIns := [][]string{{`[[0,1,1,1],[1,1,1,1],[0,1,1,1]]`}, {`[[1,0,1],[1,1,0],[1,1,0]]`}}
	sampleOuts := [][]string{{`15`}, {`7`}}
	if err := testutil.RunLeetCodeFunc(t, countSquares, sampleIns, sampleOuts); err != nil {
		t.Fatal(err)
	}
}
