// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`5`, `[[0,1,2,3,4],[2,3,4],[4,0,1,2,3]]`, 
			`2`,
		},
		{
			`3`, `[[0],[1],[2]]`, 
			`0`,
		},
		{
			`5`, `[[0,1,2,3,4],[4,3,2,1,0]]`, 
			`1`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, longestCommonSubpath, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-248/problems/longest-common-subpath/
