// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1304/F2 2400
// https://codeforces.com/problemset/status/1304/problem/F2?friends=on
func Test_cf1304F2(t *testing.T) {
	testCases := [][2]string{
		{
			`4 5 2
0 2 1 1 0
0 0 3 1 2
1 0 4 3 1
3 3 0 0 4`,
			`25`,
		},
		{
			`3 3 1
1 2 3
4 5 6
7 8 9`,
			`31`,
		},
		{
			`3 3 2
1 2 3
4 5 6
7 8 9`,
			`44`,
		},
		{
			`3 3 3
1 2 3
4 5 6
7 8 9`,
			`45`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1304F2)
}
