// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1313/D
// https://codeforces.com/problemset/status/1313/problem/D?friends=on
func Test_cf1313D(t *testing.T) {
	testCases := [][2]string{
		{
			`3 5 3
1 3
2 4
3 5`,
			`4`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1313D)
}
