// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1333/A 1000
// https://codeforces.com/problemset/status/1333/problem/A?friends=on
func Test_cf1333A(t *testing.T) {
	testCases := [][2]string{
		{
			`2
3 2
3 3`,
			`BW
WB
BB
BWB
BWW
BWB`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1333A)
}
