// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1344/C 2600
// https://codeforces.com/problemset/status/1344/problem/C?friends=on
func Test_cf1344C(t *testing.T) {
	testCases := [][2]string{
		{
			`2 1
1 2`,
			`1
AE`,
		},
		{
			`4 3
1 2
2 3
3 1`,
			`-1`,
		},
		{
			`3 2
1 3
2 3`,
			`2
AAE`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1344C)
}
