// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1367/F2
// https://codeforces.com/problemset/status/1367/problem/F2?friends=on
func Test_cf1367F2(t *testing.T) {
	testCases := [][2]string{
		{
			`9
5
4 7 2 2 9
5
3 5 8 1 7
5
1 2 2 4 5
2
0 1
3
0 1 0
4
0 1 0 0
4
0 1 0 1
4
0 1 0 2
20
16 15 1 10 0 14 0 10 3 9 2 5 4 5 17 9 10 20 0 9`,
			`2
2
0
0
1
1
1
1
16`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1367F2)
}
