// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1100/C
// https://codeforces.com/problemset/status/1100/problem/C
func Test_cf1100C(t *testing.T) {
	testCases := [][2]string{
		{
			`3 1`,
			`6.4641016`,
		},
		{
			`6 1`,
			`1.0000000`,
		},
		{
			`100 100`,
			`3.2429391`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1100C)
}
