// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1144/G 2400
// https://codeforces.com/problemset/status/1144/problem/G?friends=on
func Test_cf1144G(t *testing.T) {
	testCases := [][2]string{
		{
			`9
5 1 3 6 8 2 9 0 10`,
			`YES
1 0 0 0 0 1 0 1 0`,
		},
		{
			`5
1 2 4 0 2`,
			`NO`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1144G)
}
