// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1149/E 3200
// https://codeforces.com/problemset/status/1149/problem/E?friends=on
func Test_cf1149E(t *testing.T) {
	testCases := [][2]string{
		{
			`4 2
2 1 1 5
1 2
3 4`,
			`WIN
1 5 1 5`,
		},
		{
			`4 2
1 5 1 5
1 2
3 4`,
			`LOSE`,
		},
		{
			`3 3
314 159 265
1 2
1 3
3 2`,
			`WIN
0 0 0`,
		},
		{
			`6 4
2 2 5 5 6 6
1 3
2 4
3 5
4 6`,
			`LOSE`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1149E)
}
