// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1169/B
// https://codeforces.com/problemset/status/1169/problem/B
func TestCF1169B(t *testing.T) {
	testCases := [][2]string{
		{
			`4 6
1 2
1 3
1 4
2 3
2 4
3 4`,
			`NO`,
		},
		{
			`5 4
1 2
2 3
3 4
4 5`,
			`YES`,
		},
		{
			`300000 5
1 2
1 2
1 2
1 2
1 2`,
			`YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, CF1169B)
}
