// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1174/B 1200
// https://codeforces.com/problemset/status/1174/problem/B?friends=on
func Test_cf1174B(t *testing.T) {
	testCases := [][2]string{
		{
			`3
4 1 7`,
			`1 4 7`,
		},
		{
			`2
1 1`,
			`1 1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1174B)
}
