// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1183/H
// https://codeforces.com/problemset/status/1183/problem/H?friends=on
func Test_cf1183H(t *testing.T) {
	testCases := [][2]string{
		{
			`4 5
asdf`,
			`4`,
		},
		{
			`5 6
aaaaa`,
			`15`,
		},
		{
			`5 7
aaaaa`,
			`-1`,
		},
		{
			`10 100
ajihiushda`,
			`233`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1183H)
}
