// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1196/A
// https://codeforces.com/problemset/status/1196/problem/A
func Test_cf1196A(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1 3 4
1 10 100
10000000000000000 10000000000000000 10000000000000000
23 34 45`,
			`4
55
15000000000000000
51`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1196A)
}
