// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1198/F 2900 2026.3.16
// https://codeforces.com/problemset/status/1198/problem/F?friends=on
func Test_cf1198F(t *testing.T) {
	testCases := [][2]string{
		{
			`4
2 3 6 7`,
			`YES
2 2 1 1`,
		},
		{
			`5
6 15 35 77 22`,
			`YES
2 1 2 1 1`,
		},
		{
			`5
6 10 15 1000 75`,
			`NO`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1198F)
}
