// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1210/D 2400
// https://codeforces.com/problemset/status/1210/problem/D?friends=on
func Test_cf1210D(t *testing.T) {
	testCases := [][2]string{
		{
			`4 5
1 2
2 4
1 3
3 4
2 3
2
2
3`,
			`4
3
2`,
		},
		{
			`3 3
1 2
2 3
1 3
5
1
2
2
1
3`,
			`1
1
1
1
1
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1210D)
}
