// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1221/F
// https://codeforces.com/problemset/status/1221/problem/F?friends=on
func Test_cf1221F(t *testing.T) {
	testCases := [][2]string{
		{
			`6
0 0 2
1 0 -5
1 1 3
2 3 4
1 4 -4
3 1 -1`,
			`4
1 1 3 3`,
		},
		{
			`5
3 3 0
3 3 -3
0 2 -1
3 1 3
0 0 -2`,
			`0
1 1 1 1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1221F)
}
