// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1268/D 3200
// https://codeforces.com/problemset/status/1268/problem/D?friends=on
func Test_cf1268D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
010
001
100`,
			`0 1`,
		},
		{
			`4
0010
1000
0100
1110`,
			`-1`,
		},
		{
			`6
010000
001000
100000
111001
111100
111010`,
			`2 18`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1268D)
}
