// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1269/B
// https://codeforces.com/problemset/status/1269/problem/B?friends=on
func Test_cf1269B(t *testing.T) {
	testCases := [][2]string{
		{
			`4 3
0 0 2 1
2 0 1 1`,
			`1`,
		},
		{
			`3 2
0 0 0
1 1 1`,
			`1`,
		},
		{
			`5 10
0 0 0 1 2
2 1 0 0 0`,
			`0`,
		},
		{
			`1 1
0
0`,
			`0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1269B)
}
