// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1270/G
// https://codeforces.com/problemset/status/1270/problem/G
func Test_cf1270G(t *testing.T) {
	testCases := [][2]string{
		{
			`2
5
0 1 2 3 4
4
-3 1 1 1`,
			`1
1 
4
1 4 3 2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1270G)
}
