// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1279/B 1300
// https://codeforces.com/problemset/status/1279/problem/B?friends=on
func Test_cf1279B(t *testing.T) {
	testCases := [][2]string{
		{
			`3
7 11
2 9 1 3 18 1 4
4 35
11 9 10 7
1 8
5`,
			`2
1
0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1279B)
}
