// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc457/tasks/abc457_g ~CF2169 1928
// 提交：https://atcoder.jp/contests/abc457/submit?taskScreenName=abc457_g
// 对拍：https://atcoder.jp/contests/abc457/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc457_g&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc457/submissions?f.Status=AC&f.Task=abc457_g&orderBy=source_length
func Test_g(t *testing.T) {
	testCases := [][2]string{
		{
			`4
0 2
1 0
2 1
2 3`,
			`2`,
		},
		{
			`5
0 1
0 2
0 3
0 4
0 5`,
			`5`,
		},
		{
			`8
10 4
4 2
7 10
5 3
1 9
0 6
3 8
0 9`,
			`2`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
