// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[1,1,4,2,3]`, `5`, 
			`2`,
		},
		{
			`[5,6,7,8,9]`, `4`, 
			`-1`,
		},
		{
			`[3,2,20,1,1,3]`, `10`, 
			`5`,
		},
		{
			`[1]`, `1`,
			`1`,
		},
		{
			`[1,1]`, `2`,
			`2`,
		},
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, minOperations, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-215/problems/minimum-operations-to-reduce-x-to-zero/
