// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_d(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, countValidSubsets, "d.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/biweekly-contest-183/problems/count-non-adjacent-subsets-in-a-rooted-tree/
// https://leetcode.cn/problems/count-non-adjacent-subsets-in-a-rooted-tree/
