// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1708/B
// https://codeforces.com/problemset/status/1708/problem/B?friends=on
func Test_cf1708B(t *testing.T) {
	testCases := [][2]string{
		{
			`4
5 1 5
9 1000 2000
10 30 35
1 1000000000 1000000000`,
			`YES
1 2 3 4 5
YES
1145 1926 1440 1220 1230 1350 1001 1000 1233
NO
YES
1000000000`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1708B)
}
