// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1709/D 1700
// https://codeforces.com/problemset/status/1709/problem/D?friends=on
func Test_cf1709D(t *testing.T) {
	testCases := [][2]string{
		{
			`11 10
9 0 0 10 3 4 8 11 10 8
6
1 2 1 3 1
1 2 1 3 2
4 3 4 5 2
5 3 11 5 3
5 3 11 5 2
11 9 9 10 1`,
			`YES
NO
NO
NO
YES
YES`,
		},
		{
			`10 10
2 7 1 5 2 0 6 6 2 7
10
10 4 10 4 8
1 6 8 6 7
9 7 9 7 8
8 1 8 10 3
7 7 7 1 3
6 4 6 4 8
3 5 3 9 4
5 9 3 1 1
5 6 5 6 9
8 9 2 3 6`,
			`YES
YES
YES
YES
YES
YES
YES
YES
YES
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1709D)
}
