// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1726/E 2400
// https://codeforces.com/problemset/status/1726/problem/E?friends=on
func Test_cf1726E(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2
3
50`,
			`2
4
830690567`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1726E)
}
