// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1736/B
// https://codeforces.com/problemset/status/1736/problem/B
func Test_cf1736B(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1
343
2
4 2
3
4 2 4
4
1 1 1 1`,
			`YES
YES
NO
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1736B)
}
