// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1737/E 2500
// https://codeforces.com/problemset/status/1737/problem/E?friends=on
func Test_cf1737E(t *testing.T) {
	testCases := [][2]string{
		{
			`3
4
5
2`,
			`0
250000002
250000002
500000004
0
250000002
250000002
250000002
250000002
0
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1737E)
}
