// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1764/E 2400 2026.3.11
// https://codeforces.com/problemset/status/1764/problem/E?friends=on
func Test_cf1764E(t *testing.T) {
	testCases := [][2]string{
		{
			`6
4 16
5 3
8 12
10 7
15 1
4 16
8 12
10 7
15 1
5 3
4 16
10 7
15 1
5 3
8 12
4 16
15 1
5 3
8 12
10 7
1 1000000000
500000000 500000000
2 1000000000
1 999999999
1 1`,
			`NO
YES
YES
YES
NO
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1764E)
}
