// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1774/F2 2700 2026.5.5
// https://codeforces.com/problemset/status/1774/problem/F2?friends=on
func Test_cf1774F2(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1 8
2 3
3
3`,
			`2`,
		},
		{
			`6
1 5
1 6
2 2
3
1 4
3`,
			`5`,
		},
		{
			`12
2 1
1 15
1 9
3
1 12
2 2
1 13
3
2 1
1 9
1 8
3`,
			`17`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1774F2)
}
