// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1778/D
// https://codeforces.com/problemset/status/1778/problem/D?friends=on
func Test_cf1778D(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1
0
1
2
00
00
4
1000
1110
5
01001
10111`,
			`1
0
665496254
665496277`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1778D)
}
