// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1779/F 2500
// https://codeforces.com/problemset/status/1779/problem/F?friends=on
func Test_cf1779F(t *testing.T) {
	testCases := [][2]string{
		{
			`2
13 13
1`,
			`1
1`,
		},
		{
			`7
5 2 8 3 4 1 31
1 1 2 2 3 3`,
			`-1`,
		},
		{
			`9
3 31 1 2 7 30 7 3 1
1 1 1 2 5 5 3 4`,
			`6
3 2 3 1 2 2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1779F)
}
