// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1789/E 2500
// https://codeforces.com/problemset/status/1789/problem/E?friends=on
func Test_cf1789E(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3
1 2 4
4
1 2 7 9
4
344208 591000 4779956 5403429
5
1633 1661 1741 2134 2221`,
			`26
158
758737625
12334970`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1789E)
}
