// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/diverta2019/tasks/diverta2019_e
// 提交：https://atcoder.jp/contests/diverta2019/submit?taskScreenName=diverta2019_e
// 对拍：https://atcoder.jp/contests/diverta2019/submissions?f.LanguageName=Go&f.Status=AC&f.Task=diverta2019_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`3
1 2 3`,
			`3`,
		},
		{
			`3
1 2 2`,
			`1`,
		},
		{
			`32
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0`,
			`147483634`,
		},
		{
			`24
1 2 5 3 3 6 1 1 8 8 0 3 3 4 6 6 4 0 7 2 5 4 6 2`,
			`292`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
