// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	exampleIns := [][]string{{`[1,2,3,3]`, `[3,4,5,6]`, `[50,10,40,70]`}, {`[1,2,3,4,6]`, `[3,5,10,6,9]`, `[20,20,100,70,60]`}, {`[1,1,1]`, `[2,3,4]`, `[5,6,4]`}}
	exampleOuts := [][]string{{`120`}, {`150`}, {`6`}}
	// TODO: 测试参数的下界和上界！
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	const targetCaseNum = 0
	if err := testutil.RunLeetCodeFuncWithCase(t, jobScheduling, exampleIns, exampleOuts, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
