// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [e]")
	exampleIns := [][]string{{`6`, `[[1, 2], [1, 6], [2, 3], [2, 5], [1, 4]]`, `[[1, 1, 500], [2, 2, 50], [3, 1], [2, 6, 15], [3, 1]]`}}
	exampleOuts := [][]string{{`[650,665]`}}
	// TODO: 测试参数的下界和上界！
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithCase(t, bonus, exampleIns, exampleOuts, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/season/2019-fall/problems/coin-bonus/
