// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc355/tasks/abc355_f
// 提交：https://atcoder.jp/contests/abc355/submit?taskScreenName=abc355_f
// 对拍：https://atcoder.jp/contests/abc355/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc355_f&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc355/submissions?f.Status=AC&f.Task=abc355_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`4 4
1 2 6
2 3 5
2 4 4
1 3 3
1 2 3
1 4 10
3 4 1`,
			`12
10
10
7`,
		},
		{
			`8 6
1 8 8
1 6 10
1 5 8
2 6 6
6 7 6
1 3 9
2 4 7
1 3 4
1 6 7
3 4 6
1 5 1
7 8 4
3 5 3`,
			`49
46
45
38
34
33`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
