// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P1282
func Test_p1282(t *testing.T) {
	testCases := [][2]string{
		{
			`4
6 1
1 5
1 3
1 2`,
			`1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p1282)
}
