// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P1297
func Test_p1297(t *testing.T) {
	testCases := [][2]string{
		{
			`3 2 0 4 1`,
			`1.167`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p1297)
}
