// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/practice2/tasks/practice2_d
// 提交：https://atcoder.jp/contests/practice2/submit?taskScreenName=practice2_d
// 对拍：https://atcoder.jp/contests/practice2/submissions?f.LanguageName=Go&f.Status=AC&f.Task=practice2_d&orderBy=source_length
// 最短：https://atcoder.jp/contests/practice2/submissions?f.Status=AC&f.Task=practice2_d&orderBy=source_length
func Test_d(t *testing.T) {
	testCases := [][2]string{
		{
			`3 3
#..
..#
...`,
			`3
#><
vv#
^^.`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
