// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc215/tasks/abc215_f
// 提交：https://atcoder.jp/contests/abc215/submit?taskScreenName=abc215_f
// 对拍：https://atcoder.jp/contests/abc215/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc215_f&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc215/submissions?f.Status=AC&f.Task=abc215_f&orderBy=source_length
func Test_f(t *testing.T) {
	testCases := [][2]string{
		{
			`3
0 3
3 1
4 10`,
			`4`,
		},
		{
			`4
0 1
0 4
0 10
0 6`,
			`0`,
		},
		{
			`8
897 729
802 969
765 184
992 887
1 104
521 641
220 909
380 378`,
			`801`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
