// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	exampleIns := [][]string{{`[["#",".","#","#",".","#"],[".","#","#","#","#","."],["#",".","#","#",".","#"]]`}, {`[[".","#"],["#","#"],["#","."],["#","#"],[".","#"]]`}, {`[["#",".",".",".","#"],[".","#",".","#","."],[".",".","#",".","."],[".","#",".","#","."],["#",".",".",".","#"]]`}}
	exampleOuts := [][]string{{`4`}, {`3`}, {`10`}}
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	if err := testutil.RunLeetCodeFuncWithCase(t, maxStudents, exampleIns, exampleOuts, 0); err != nil {
		t.Fatal(err)
	}
}
