// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/437/B
// https://codeforces.com/problemset/status/437/problem/B
func Test_cf437B(t *testing.T) {
	testCases := [][2]string{
		{
			`5 5`,
			`2
4 5`,
		},
		{
			`4 3`,
			`3
2 3 1`,
		},
		{
			`5 1`,
			`-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf437B)
}
