// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/451/E
// https://codeforces.com/problemset/status/451/problem/E
func Test_cf451E(t *testing.T) {
	testCases := [][2]string{
		{
			`2 3
1 3`,
			`2`,
		},
		{
			`2 4
2 2`,
			`1`,
		},
		{
			`3 5
1 3 2`,
			`3`,
		},
		{
			`1 1
0`,
			`0`,
		},
		{
			`1 0
1`,
			`1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf451E)
}
