// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/498/E 2700
// https://codeforces.com/problemset/status/498/problem/E?friends=on
func Test_cf498E(t *testing.T) {
	testCases := [][2]string{
		{
			`0 1 0 0 0 0 0`,
			`1`,
		},
		{
			`0 2 0 0 0 0 0`,
			`7`,
		},
		{
			`1 1 1 0 0 0 0`,
			`9`,
		},
		{
			`5 1 0 3 0 0 1`,
			`411199181`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf498E)
}
