// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`"abcdefd"`, `"d"`, 
			`"dcbaefd"`,
		},
		{
			`"xyxzxe"`, `"z"`, 
			`"zxyxxe"`,
		},
		{
			`"abcd"`, `"z"`, 
			`"abcd"`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, reversePrefix, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-258/problems/reverse-prefix-of-word/
