// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1900/C
// https://codeforces.com/problemset/status/1900/problem/C?friends=on
func Test_cf1900C(t *testing.T) {
	testCases := [][2]string{
		{
			`5
3
LRU
2 3
0 0
0 0
3
ULR
3 2
0 0
0 0
2
LU
0 2
0 0
4
RULR
3 0
0 0
0 4
2 0
7
LLRRRLU
5 2
3 6
0 0
7 0
4 0
0 0
0 0`,
			`0
1
1
3
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1900C)
}
