// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/1907/problem/F
// https://codeforces.com/problemset/status/1907/problem/F
func Test_cf1907F(t *testing.T) {
	testCases := [][2]string{
		{
			`11
5
3 2 1 5 4
5
1 1 2 1 1
4
3 7 10 5
5
1 2 3 4 5
2
5 1
3
3 4 1
5
4 1 3 4 4
3
5 1 1
4
2 5 5 4
5
2 2 1 1 2
2
5 5`,
			`3
2
-1
0
1
1
3
1
2
2
0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1907F)
}
