// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/1907/problem/D
// https://codeforces.com/problemset/status/1907/problem/D
func Test_cf1907D(t *testing.T) {
	testCases := [][2]string{
		{
			`4
5
1 5
3 4
5 6
8 10
0 1
3
0 2
0 1
0 3
3
3 8
10 18
6 11
4
10 20
0 5
15 17
2 2`,
			`7
0
5
13`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1907D)
}
