// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/1913/problem/C
// https://codeforces.com/problemset/status/1913/problem/C
func Test_cf1913C(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1 0
1 0
1 0
2 3
2 4`,
			`YES
NO`,
		},
		{
			`7
1 0
1 1
1 2
1 10
2 4
2 6
2 7`,
			`YES
YES
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1913C)
}
