// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1916/H2 2700
// https://codeforces.com/problemset/status/1916/problem/H2?friends=on
func Test_cf1916H2(t *testing.T) {
	testCases := [][2]string{
		{
			`3 2 3`,
			`1 49 294 168`,
		},
		{
			`1 51549919 2`,
			`1 51549918 0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1916H2)
}
