// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1919/D
// https://codeforces.com/problemset/status/1919/problem/D
func Test_cf1919D(t *testing.T) {
	testCases := [][2]string{
		{
			`2
5
2 1 0 1 1
5
1 0 2 1 3`,
			`YES
NO`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1919D)
}
