// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1919/C
// https://codeforces.com/problemset/status/1919/problem/C
func Test_cf1919C(t *testing.T) {
	testCases := [][2]string{
		{
			`5
5
1 2 3 4 5
8
8 2 3 1 1 7 4 3
5
3 3 3 3 3
1
1
2
2 1`,
			`3
1
0
0
0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1919C)
}
