// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1932/C
// https://codeforces.com/problemset/status/1932/problem/C?friends=on
func Test_cf1932C(t *testing.T) {
	testCases := [][2]string{
		{
			`4
4 6
3 1 4 2
LRRL
5 1
1 1 1 1 1
LLLLL
6 8
1 2 3 4 5 6
RLLLRR
1 10000
10000
R`,
			`0 2 4 1 
0 0 0 0 0 
0 0 0 4 4 4 
0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1932C)
}
