// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1941/E 1600 2026.3.17
// https://codeforces.com/problemset/status/1941/problem/E?friends=on
func Test_cf1941E(t *testing.T) {
	testCases := [][2]string{
		{
			`5
3 11 1 4
0 1 2 3 4 5 4 3 2 1 0
0 1 2 3 2 1 2 3 3 2 0
0 1 2 3 5 5 5 5 5 2 0
4 4 2 1
0 3 3 0
0 2 1 0
0 1 2 0
0 3 3 0
4 5 2 5
0 1 1 1 0
0 2 2 2 0
0 2 1 1 0
0 3 2 1 0
1 8 1 1
0 10 4 8 4 4 2 0
4 5 3 2
0 8 4 4 0
0 3 4 8 0
0 8 1 10 0
0 10 1 5 0`,
			`4
8
4
15
14`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1941E)
}
