// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1943/D2
// https://codeforces.com/problemset/status/1943/problem/D2?friends=on
func Test_cf1943D2(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3 1 998244853
4 1 998244353
3 2 998244353
343 343 998244353`,
			`4
7
10
456615865`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1943D2)
}
