// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/1950/problem/G
// https://codeforces.com/problemset/status/1950/problem/G
func Test_cf1950G(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1
pop taylorswift
4
electronic themotans
electronic carlasdreams
pop themotans
pop irinarimes
7
rap eminem
rap drdre
rap kanyewest
pop taylorswift
indierock arcticmonkeys
indierock arcticmonkeys
punkrock theoffspring
4
a b
c d
e f
g h`,
			`0
0
4
3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1950G)
}
