// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1954/B
// https://codeforces.com/problemset/status/1954/problem/B?friends=on
func Test_cf1954B(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3
2 2 2
5
1 2 1 2 1
1
1
7
3 3 3 5 3 3 3`,
			`-1
1
-1
3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1954B)
}
