// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/1955/problem/G
// https://codeforces.com/problemset/status/1955/problem/G
func Test_cf1955G(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2 3
30 20 30
15 25 40
3 3
12 4 9
3 12 2
8 3 12
2 4
2 4 6 8
1 3 6 9`,
			`10
3
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1955G)
}
