// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1973/B
// https://codeforces.com/problemset/status/1973/problem/B?friends=on
func Test_cf1973B(t *testing.T) {
	testCases := [][2]string{
		{
			`7
1
0
3
2 2 2
3
1 0 2
5
3 0 1 4 2
5
2 0 4 0 2
7
0 0 0 0 1 2 4
8
0 1 3 2 2 1 0 3`,
			`1
1
3
4
4
7
3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1973B)
}
