// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1974/C
// https://codeforces.com/problemset/status/1974/problem/C?friends=on
func Test_cf1974C(t *testing.T) {
	testCases := [][2]string{
		{
			`8
5
3 2 2 2 3
5
1 2 1 2 1
8
1 2 3 2 2 3 4 2
4
2 1 1 1
8
2 1 1 2 1 1 1 1
7
2 1 1 1 1 1 1
6
2 1 1 1 1 1
5
2 1 1 1 1`,
			`2
0
3
1
8
4
3
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1974C)
}
