// Generated by copypasta/template/generator_test.go
package main

// https://codeforces.com/problemset/problem/1977/E 2600 2026.3.23
// https://codeforces.com/problemset/status/1977/problem/E?friends=on
