// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/contest/1979/problem/C
// https://codeforces.com/problemset/status/1979/problem/C?friends=on
func Test_cf1979C(t *testing.T) {
	testCases := [][2]string{
		{
			`6
3
3 2 7
2
3 3
5
5 5 5 5 5
6
7 9 3 17 9 13
3
6 3 2
5
9 4 6 8 3`,
			`27 41 12 
1 1 
-1
1989 1547 4641 819 1547 1071 
-1
8 18 12 9 24`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1979C)
}
