// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1984/C2
// https://codeforces.com/problemset/status/1984/problem/C2
func Test_cf1984C2(t *testing.T) {
	testCases := [][2]string{
		{
			`5
4
2 -5 3 -3
8
1 4 3 4 1 4 3 4
3
-1 -2 -3
4
-1000000000 1000000000 1000000000 1000000000
4
1 9 8 4`,
			`12
256
1
8
16`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1984C2)
}
