// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1985/G
// https://codeforces.com/problemset/status/1985/problem/G
func Test_cf1985G(t *testing.T) {
	testCases := [][2]string{
		{
			`6
0 1 4
0 2 7
1 2 1
1 2 3
582 74663 3
0 3 1`,
			`2
3
90
12
974995667
999`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1985G)
}
