// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1987/C
// https://codeforces.com/problemset/status/1987/problem/C?friends=on
func Test_cf1987C(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3
1 1 2
2
3 1
1
9
5
7 4 4 3 2`,
			`4
3
9
7`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1987C)
}
