// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1991/G 2700 2026.4.24
// https://codeforces.com/problemset/status/1991/problem/G?friends=on
func Test_cf1991G(t *testing.T) {
	testCases := [][2]string{
		{
			`1
4 5 3 6
HVVHHV`,
			`1 1
2 1
1 1
2 3
3 3
2 2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1991G)
}
