// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1992/F 1900 2026.3.17
// https://codeforces.com/problemset/status/1992/problem/F?friends=on
func Test_cf1992F(t *testing.T) {
	testCases := [][2]string{
		{
			`8
6 4
2 3 6 2 1 2
9 100000
50000 25000 12500 6250 3125 2 4 8 16
5 2
1 1 1 1 1
8 6
4 3 4 3 4 3 4 3
7 12
6 11 1 3 11 10 2
10 5
2 4 4 2 4 4 4 3 1 1
7 8
4 6 5 1 2 4 1
8 27
3 9 17 26 2 20 9 3`,
			`3
2
1
1
2
1
3
3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1992F)
}
