// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`4 2 3
0 1 3 1
1 1 4 1
2 0 2 2`,
			`YES`,
		},
		{
			`2 2 4
0 0 2 2
2 0 0 1
0 2 1 2
1 1 2 1`,
			`NO`,
		},
		{
			`5 5 7
0 0 2 4
2 3 4 5
3 5 5 2
5 5 5 4
0 3 5 1
2 2 4 4
0 5 4 1`,
			`YES`,
		},
		{
			`1 1 2
0 0 1 1
1 0 0 1`,
			`NO`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 2, run)
	//testutil.AssertEqualRunResults(t, testCases, 0, runAC, run)
}
// https://atcoder.jp/contests/arc076/tasks/arc076_c
// https://atcoder.jp/contests/arc076/submit?taskScreenName=arc076_c
