// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_c(t *testing.T) {
	examples := [][]string{
		{
			`"leetcode"`, `7`, `20`, `2`, `0`, 
			`"ee"`,
		},
		{
			`"fbxzaad"`, `31`, `100`, `3`, `32`, 
			`"fbx"`,
		},
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, subStrHash, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-278/problems/find-substring-with-given-hash-value/
