// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

// 1e9~1e18 √n logn 1     二分 二进制
// 1e5~1e6  nlogn nαn n   二分 RMQ 并查集
// 1e3~1e4  n^2 n√n       RMQ DP 分块
// 300~500  n^3           DP 二分图
func Test(t *testing.T) {
	t.Log("Current test is [b]")
	exampleIns := [][]string{{`["ABC","ACB","ABC","ACB","ACB"]`}, {`["WXYZ","XYZW"]`}, {`["ZMNAGUEDSJYLBOPHRQICWFXTVK"]`}, {`["BCA","CAB","CBA","ABC","ACB","BAC"]`}, {`["M","M","M","M"]`}}
	exampleOuts := [][]string{{`"ACB"`}, {`"XWYZ"`}, {`"ZMNAGUEDSJYLBOPHRQICWFXTVK"`}, {`"ABC"`}, {`"M"`}}
	// TODO: 测试参数的下界和上界！
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithCase(t, rankTeams, exampleIns, exampleOuts, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-178/problems/rank-teams-by-votes/
