// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_b(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, minAbsDiff, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-452/problems/minimum-absolute-difference-in-sliding-submatrix/
// https://leetcode.cn/problems/minimum-absolute-difference-in-sliding-submatrix/
