// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_d(t *testing.T) {
	examples := [][]string{
		{
			`[1,2,3,4,5]`, `2`,
			`7`,
		},
		{
			`[1,2,3,4]`, `5`,
			`0`,
		},

	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, coutPairs, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-281/problems/count-array-pairs-divisible-by-k/
