// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/908/G
// https://codeforces.com/problemset/status/908/problem/G?friends=on
func Test_cf908G(t *testing.T) {
	testCases := [][2]string{
		{
			`21`,
			`195`,
		},
		{
			`345342`,
			`390548434`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf908G)
}
