// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/914/D 1900 2026.4.27
// https://codeforces.com/problemset/status/914/problem/D?friends=on
func Test_cf914D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2 6 3
4
1 1 2 2
1 1 3 3
2 1 9
1 1 3 2`,
			`YES
YES
NO`,
		},
		{
			`5
1 2 3 4 5
6
1 1 4 2
2 3 6
1 1 4 2
1 1 5 2
2 5 10
1 1 5 2`,
			`NO
YES
NO
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf914D)
}
