// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/920/C
// https://codeforces.com/problemset/status/920/problem/C
func TestCF920C(t *testing.T) {
	testCases := [][2]string{
		{
			`6
1 2 5 3 4 6
01110`,
			`YES`,
		},
		{
			`6
1 2 5 3 4 6
01010`,
			`NO`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, CF920C)
}
