// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/922/F 2400 2026.4.13
// https://codeforces.com/problemset/status/922/problem/F?friends=on
func Test_cf922F(t *testing.T) {
	testCases := [][2]string{
		{
			`3 3`,
			`No`,
		},
		{
			`6 6`,
			`Yes
5
1 2 4 5 6`,
		},
		{
			`8 3`,
			`Yes
4
2 4 5 8`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf922F)
}
