// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/938/F 2700
// https://codeforces.com/problemset/status/938/problem/F?friends=on
func Test_cf938F(t *testing.T) {
	testCases := [][2]string{
		{
			`adcbca`,
			`aba`,
		},
		{
			`abacabadabacaba`,
			`aabacaba`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf938F)
}
