// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/946/G
// https://codeforces.com/problemset/status/946/problem/G?friends=on
func Test_cf946G(t *testing.T) {
	testCases := [][2]string{
		{
			`5
5 4 3 2 1`,
			`3`,
		},
		{
			`5
1 2 8 9 5`,
			`0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf946G)
}
