// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/958/C3 2500
// https://codeforces.com/problemset/status/958/problem/C3?friends=on
func Test_cf958C3(t *testing.T) {
	testCases := [][2]string{
		{
			`4 3 10
3 4 7 2`,
			`6`,
		},
		{
			`10 5 12
16 3 24 13 9 8 7 5 12 12`,
			`13`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf958C3)
}
