// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/976/C
// https://codeforces.com/problemset/status/976/problem/C
func Test_cf976C(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1 10
2 9
3 9
2 3
2 9`,
			`2 1`,
		},
		{
			`3
1 5
2 6
6 20`,
			`-1 -1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf976C)
}
