// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/992/E 2500
// https://codeforces.com/problemset/status/992/problem/E?friends=on
func Test_cf992E(t *testing.T) {
	testCases := [][2]string{
		{
			`2 1
1 3
1 2`,
			`-1`,
		},
		{
			`3 4
2 2 3
1 1
1 2
2 4
3 6`,
			`3
2
-1
3`,
		},
		{
			`10 7
0 3 1 4 6 2 7 8 10 1
2 5
1 3
9 36
4 10
4 9
1 2
1 0`,
			`1
-1
9
-1
4
-1
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf992E)
}
