// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`1`, 
			`true`,
		},
		{
			`2`, 
			`false`,
		},
		{
			`4`, 
			`true`,
		},
		{
			`7`, 
			`false`,
		},
		{
			`17`, 
			`false`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, winnerSquareGame, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-30/problems/stone-game-iv/
