// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`"H..H"`, 
			`2`,
		},
		{
			`".H.H."`, 
			`1`,
		},
		{
			`".HHH."`, 
			`-1`,
		},
		{
			`"H"`, 
			`-1`,
		},
		{
			`"."`, 
			`0`,
		},
		{
			`"H.H.H.H"`,
			`2`,
		},
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, minimumBuckets, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-66/problems/minimum-number-of-buckets-required-to-collect-rainwater-from-houses/
