// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_b(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, countVisiblePeople, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/biweekly-contest-179/problems/direction-assignments-with-exactly-k-visible-people/
// https://leetcode.cn/problems/direction-assignments-with-exactly-k-visible-people/
