// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`5`, `[[2,1],[4,1]]`, 
			`2`,
		},
		{
			`6`, `[]`, 
			`5`,
		},
		{
			`10`, `[[5,3],[2,5],[7,4],[10,3]]`, 
			`5`,
		},
		// TODO 测试入参最小的情况
		{
			`5`, `[[4,100], [5,0]]`,
			`2`,
		},
	}
	targetCaseNum := -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, maxBuilding, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-238/problems/maximum-building-height/
