// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

// 1e9~1e18 √n logn 1     二分 二进制
// 1e5~1e6  nlogn nαn n   二分 RMQ 并查集
// 1e3~1e4  n^2 n√n       RMQ DP 分块
// 300~500  n^3           DP 二分图
func Test(t *testing.T) {
	t.Log("Current test is [d]")
	exampleIns := [][]string{{`[8,1,9]`}, {`[8,6,7,1,0]`}, {`[1]`}, {`[0,0,0,0,0,0]`}}
	exampleOuts := [][]string{{`"981"`}, {`"8760"`}, {`""`}, {`"0"`}}
	// TODO: 测试参数的下界和上界！
	// custom test cases or WA cases.
	exampleIns = append(exampleIns, []string{`[5,8]`})
	exampleOuts = append(exampleOuts, []string{`""`})
	targetCaseNum := 5
	if err := testutil.RunLeetCodeFuncWithCase(t, largestMultipleOfThree, exampleIns, exampleOuts, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-177/problems/largest-multiple-of-three/
