// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	exampleIns := []string{`
["StockSpanner","next","next","next","next","next","next","next"]
[[],[100],[80],[60],[70],[60],[75],[85]]
`}
	exampleOuts := []string{`
[null,1,1,1,2,1,4,6]
`}
	// custom test cases or WA cases.
	// TODO: 测试参数的下界和上界！
	//exampleIns = append(exampleIns, ``)
	//exampleOuts = append(exampleOuts, ``)
	targetCaseNum := 0
	if err := testutil.RunLeetCodeClassWithCase(t, Constructor, exampleIns, exampleOuts, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-101/problems/online-stock-span/
