// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc290/submit?taskScreenName=abc290_e
// 对拍：https://atcoder.jp/contests/abc290/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc290_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`5
5 2 1 2 2`,
			`9`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/abc290/tasks/abc290_e
