// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`3
1 3
2 3`,
			`7`,
		},
		{
			`2
1 2`,
			`3`,
		},
		{
			`10
5 3
5 7
8 9
1 9
9 10
8 4
7 4
6 10
7 2`,
			`113`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
	//testutil.AssertEqualRunResults(t, testCases, 0, runAC, run)
}
// https://atcoder.jp/contests/abc173/tasks/abc173_f
// https://atcoder.jp/contests/abc173/submit?taskScreenName=abc173_f
