// Code generated by copypasta/template/nowcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	testutil2 "github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

var examples = [][]string{
	{
		`1`,
		`0`,
	},
	{
		`5`,
		`5`,
	},
	{
		`18`,
		`65`,
	},
	{
		`19`,
		`105`,
	},
	{
		`3`,
		`1`,
	},
}

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	targetCaseNum := 2
	if err := testutil.RunLeetCodeFuncWithExamples(t, cowModCount, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}

// https://ac.nowcoder.com/acm/contest/9005/c

func TestCompare(t *testing.T) {
	//rand.Seed(time.Now().UnixNano())
	inputGenerator := func() int64 {
		rg := testutil2.NewRandGenerator()
		n := rg.Int(1, 100)
		return int64(n)
	}

	runAC := func(n int64) (ans int64) {
		for i := int64(1); i <= n; i++ {
			a, b := n/i, n%i
			ans += a * b
		}
		const mod int64 = 1e9 + 7
		ans %= mod
		return
	}

	// test examples first
	if err := testutil.RunLeetCodeFuncWithExamples(t, runAC, examples, 0); err != nil {
		t.Fatal(err)
	}
	testutil.CompareInf(t, inputGenerator, runAC, cowModCount)
}
