// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`3`, `[[0,1,2],[1,2,4],[2,0,8],[1,0,16]]`, `[[0,1,2],[0,2,5]]`, 
			`[false,true]`,
		},
		{
			`5`, `[[0,1,10],[1,2,5],[2,3,9],[3,4,13]]`, `[[0,4,14],[1,4,13]]`, 
			`[true,false]`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, distanceLimitedPathsExist, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-220/problems/checking-existence-of-edge-length-limited-paths/
