// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/arc107/tasks/arc107_d
// 提交：https://atcoder.jp/contests/arc107/submit?taskScreenName=arc107_d
// 对拍：https://atcoder.jp/contests/arc107/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc107_d&orderBy=source_length
// 最短：https://atcoder.jp/contests/arc107/submissions?f.Status=AC&f.Task=arc107_d&orderBy=source_length
func Test_d(t *testing.T) {
	testCases := [][2]string{
		{
			`4 2`,
			`2`,
		},
		{
			`2525 425`,
			`687232272`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
