// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`4`, `[[0,1],[0,3],[1,2],[1,3]]`, 
			`4`,
		},
		{
			`5`, `[[0,1],[0,3],[1,2],[1,3],[2,3],[2,4]]`, 
			`5`,
		},
		{
			`8`, `[[0,1],[1,2],[2,3],[2,4],[5,6],[5,7]]`, 
			`5`,
		},
		// TODO 测试参数的下界和上界
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, maximalNetworkRank, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-210/problems/maximal-network-rank/
