// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`[[0,5],[1,2],[0,2],[0,5],[1,3]]`, `5`, 
			`[0,2,0,0,0]`,
		},
		{
			`[[1,1],[2,2],[2,3]]`, `4`, 
			`[1,1,0,0]`,
		},
		// TODO 测试入参最小的情况
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, findingUsersActiveMinutes, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-235/problems/finding-the-users-active-minutes/
