// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_b(t *testing.T) {
	examples := [][]string{
		{
			`"abdcdbc"`, `"ac"`, 
			`4`,
		},
		{
			`"aabb"`, `"ab"`, 
			`6`,
		},
		{
			`"iekbksdsmuuzwxbpmcngsfkjvpzuknqguzvzik"`, `"mp"`,
			`5`,
		},
		{
			`"fwymvreuftzgrcrxczjacqovduqaiig"`, `"yy"`,
			`1`,
		},
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, maximumSubsequenceCount, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-74/problems/maximize-number-of-subsequences-in-a-string/
