// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`101`,
			`4`,
		},
		{
			`2`,
			`-1`,
		},
		{
			`999983`,
			`999982`,
		},
		// TODO 测试参数的下界和上界
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/abc174/tasks/abc174_c
// https://atcoder.jp/contests/abc174/submit?taskScreenName=abc174_c
