// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[3,1,4,2]`, `6`, 
			`1`,
		},
		{
			`[6,3,5,2]`, `9`, 
			`2`,
		},
		{
			`[1,2,3]`, `3`, 
			`0`,
		},
		{
			`[1,2,3]`, `7`, 
			`-1`,
		},
		{
			`[1000000000,1000000000,1000000000]`, `3`, 
			`0`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, minSubarray, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-35/problems/make-sum-divisible-by-p/
