// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_a(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, sumDivisibleByK, "a.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-471/problems/sum-of-elements-with-frequency-divisible-by-k/
// https://leetcode.cn/problems/sum-of-elements-with-frequency-divisible-by-k/
