// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`[2,3,3,2]`, `[[0,1],[1,2],[1,3]]`, 
			`[-1,0,0,1]`,
		},
		{
			`[5,6,10,2,3,6,15]`, `[[0,1],[0,2],[1,3],[1,4],[2,5],[2,6]]`, 
			`[-1,0,-1,0,0,0,-1]`,
		},
		// TODO 测试入参最小的情况
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, getCoprimes, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-46/problems/tree-of-coprimes/
