// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`4`, `2`, `6`, 
			`2`,
		},
		{
			`6`, `1`, `10`, 
			`3`,
		},
		// TODO 测试入参最小的情况
		{
			`1`, `0`, `1`,
			`1`,
		},
		{
			`2`, `0`, `2`,
			`1`,
		},
		{
			`3`, `0`, `3`,
			`1`,
		},
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, maxValue, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-233/problems/maximum-value-at-a-given-index-in-a-bounded-array/
