// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`[2,2,3,3]`, `5`, 
			`14`,
		},
		{
			`[1,1,1,4,2,3]`, `4`, 
			`30`,
		},
		{
			`[7,7,7,7,7,7,7]`, `8`, 
			`49`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, wateringPlants, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-268/problems/watering-plants/
