// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1808/E3 2800
// https://codeforces.com/problemset/status/1808/problem/E3?friends=on
func Test_cf1808E3(t *testing.T) {
	testCases := [][2]string{
		{
			`3 2 1000000007`,
			`4`,
		},
		{
			`3 4 1000000007`,
			`28`,
		},
		{
			`1 1 813483257`,
			`1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1808E3)
}
