// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1809/F 2500
// https://codeforces.com/problemset/status/1809/problem/F?friends=on
func Test_cf1809F(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3 5
3 4 4
1 2 2
5 7
1 3 2 5 1
2 1 1 1 2
4 3
1 2 1 3
2 2 2 2
3 2
2 2 2
1 2 1`,
			`17 19 17 
13 12 12 12 14 
14 14 14 14 
8 8 8`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1809F)
}
