// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1814/D 2500 2026.6.11
// https://codeforces.com/problemset/status/1814/problem/D?friends=on
func Test_cf1814D(t *testing.T) {
	testCases := [][2]string{
		{
			`5
4 2
6 3 13 7
1 2 1 2
3 2
100 101 102
100 99 98
5 0
1 12 4 4 3
12 1 3 3 4
2 50
1000 10
1000000000 1
3 5
1 19 11
49 4 72`,
			`2
3
0
1
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1814D)
}
