// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1815/A
// https://codeforces.com/problemset/status/1815/problem/A
func Test_cf1815A(t *testing.T) {
	testCases := [][2]string{
		{
			`5
3
1 3 2
2
2 1
4
1 3 5 7
4
2 1 4 3
5
5 4 3 2 1`,
			`YES
NO
YES
NO
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1815A)
}
