// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1821/E
// https://codeforces.com/problemset/status/1821/problem/E
func Test_cf1821E(t *testing.T) {
	testCases := [][2]string{
		{
			`7
0
()
0
(())
1
(())
5
()
1
(()()(()))
2
((())()(()())((())))
3
((())()(()())((())))`,
			`0
1
0
0
1
4
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1821E)
}
