// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1837/C 1000
// https://codeforces.com/problemset/status/1837/problem/C?friends=on
func Test_cf1837C(t *testing.T) {
	testCases := [][2]string{
		{
			`4
??01?
10100
1??10?
0?1?10?10`,
			`00011
10100
111101
011110010`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1837C)
}
