// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1842/H 3000
// https://codeforces.com/problemset/status/1842/problem/H?friends=on
func Test_cf1842H(t *testing.T) {
	testCases := [][2]string{
		{
			`3 2
0 1 2
1 3 3`,
			`748683265`,
		},
		{
			`3 3
0 1 2
0 1 3
0 2 3`,
			`748683265`,
		},
		{
			`3 4
0 1 2
0 1 3
1 2 3
1 2 2`,
			`935854081`,
		},
		{
			`4 4
0 1 2
0 3 4
1 1 3
1 2 4`,
			`0`,
		},
		{
			`8 12
0 1 2
0 2 3
1 3 4
0 1 4
0 5 6
0 6 7
1 7 8
0 5 8
1 3 7
1 3 8
1 4 7
1 4 8`,
			`997687297`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1842H)
}
