// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1845/C 1400
// https://codeforces.com/problemset/status/1845/problem/C?friends=on
func Test_cf1845C(t *testing.T) {
	testCases := [][2]string{
		{
			`5
88005553535123456
2
50
56
123412341234
3
111
444
1234
4
4321
4321
459
2
49
59
00010
2
10
11`,
			`YES
NO
YES
NO
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1845C)
}
