// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1846/G 1900
// https://codeforces.com/problemset/status/1846/problem/G?friends=on
func Test_cf1846G(t *testing.T) {
	testCases := [][2]string{
		{
			`4
5 4
10011
3
10000
00110
3
00101
00000
3
01010
00100
5
11010
00100
4 1
0000
10
1011
0100
2 2
11
2
10
01
3
01
10
2 3
11
3
01
10
3
10
00
4
10
01`,
			`8
0
-1
6`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1846G)
}
