// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1847/B
// https://codeforces.com/problemset/status/1847/problem/B?friends=on
func Test_cf1847B(t *testing.T) {
	testCases := [][2]string{
		{
			`3
3
1 2 3
5
2 3 1 5 2
4
5 7 12 6`,
			`1
2
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1847B)
}
