// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1849/C
// https://codeforces.com/problemset/status/1849/problem/C
func Test_cf1849C(t *testing.T) {
	testCases := [][2]string{
		{
			`3
6 5
101100
1 2
1 3
2 4
5 5
1 6
6 4
100111
2 2
1 4
1 3
1 2
1 1
0
1 1`,
			`3
3
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1849C)
}
