// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1860/E 2400
// https://codeforces.com/problemset/status/1860/problem/E?friends=on
func Test_cf1860E(t *testing.T) {
	testCases := [][2]string{
		{
			`codecode
3
1 7
3 5
3 6`,
			`3
2
2`,
		},
		{
			`abcdefghij
3
1 9
9 1
5 5`,
			`8
8
0`,
		},
		{
			`aaaaaaaaaaaa
4
10 8
3 7
6 1
11 11`,
			`1
1
1
0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1860E)
}
