// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1866/K
// https://codeforces.com/problemset/status/1866/problem/K?friends=on
func Test_cf1866K(t *testing.T) {
	testCases := [][2]string{
		{
			`7
5 1 2
1 4 2
3 4 1
2 5 3
6 1 6
4 7 2
2
4 3
3 2`,
			`18
11`,
		},
		{
			`3
1 2 1000000000
2 3 1000000000
1
2 1000000000`,
			`2000000000000000000`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1866K)
}
