// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1874/B
// https://codeforces.com/problemset/status/1874/problem/B?friends=on
func Test_cf1874B(t *testing.T) {
	testCases := [][2]string{
		{
			`10
1 0 1 1 1
3 3 1 2 1
1 6 0 7 1
2 4 4 9 8
21 4 0 17 28
50 50 0 0 39
95 33 1 33 110
138 202 174 64 108
78 340 68 340 461
457 291 491 566 766`,
			`1
-1
2
-1
-1
2
1
4
1
3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1874B)
}
