// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1879/C
// https://codeforces.com/problemset/status/1879/problem/C
func Test_cf1879C(t *testing.T) {
	testCases := [][2]string{
		{
			`3
10010
111
0101`,
			`1 2
2 6
0 1`,
		},
		{
			`1
1100`,
			`2 8`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1879C)
}
