// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1895/C
// https://codeforces.com/problemset/status/1895/problem/C
func Test_cf1895C(t *testing.T) {
	testCases := [][2]string{
		{
			`10
5 93746 59 3746 593 746 5937 46 59374 6`,
			`20`,
		},
		{
			`5
2 22 222 2222 22222`,
			`13`,
		},
		{
			`3
1 1 1`,
			`9`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1895C)
}
