// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1895/D
// https://codeforces.com/problemset/status/1895/problem/D
func Test_cf1895D(t *testing.T) {
	testCases := [][2]string{
		{
			`4
2 1 2`,
			`0 2 3 1`,
		},
		{
			`6
1 6 1 4 1`,
			`2 3 5 4 0 1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1895D)
}
