// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`"abcavv"`,
			`"bcvvaa"`,
		},

		// TODO 测试参数的下界和上界

	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, change, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
