// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`3`,`10`,
			`2`,
		},

		// TODO 测试参数的下界和上界
		{
			`1`,`1`,
			`0`,
		},
		{
			`1`,`2`,
			`1`,
		},
		{
			`1`,`3`,
			`2`,
		},
		{
			`3`,`3`,
			`0`,
		},
		{
			`1`,`10`,
			`4`,
		},
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, solve, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
