// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	exampleIns := [][]string{{`"ABCABC"`, `"ABC"`}, {`"ABABAB"`, `"ABAB"`}, {`"LEET"`, `"CODE"`}}
	exampleOuts := [][]string{{`"ABC"`}, {`"AB"`}, {`""`}}
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	if err := testutil.RunLeetCodeFunc(t, gcdOfStrings, exampleIns, exampleOuts); err != nil {
		t.Fatal(err)
	}
}
