// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`["a","abc","bc","d"]`, `"abc"`, 
			`3`,
		},
		{
			`["a","b","c"]`, `"aaaaabbbbb"`, 
			`2`,
		},
		{
			`["a","a","a"]`, `"ab"`, 
			`3`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, numOfStrings, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-254/problems/number-of-strings-that-appear-as-substrings-in-word/
