// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_d(t *testing.T) {
	examples := [][]string{
		{
			`[6,2,3,4,5,5]`, 
			`18`,
		},
		{
			`[7,7,7,7,7,7,7]`, 
			`28`,
		},
		{
			`[4]`, 
			`0`,
		},
		// TODO 测试参数的下界和上界
		{
			`[5,5]`,
			`5`,
		},
		{
			`[6,1]`,
			`1`,
		},
	}
	if err := testutil.RunLeetCodeFuncWithExamples(t, stoneGameV, examples, 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-203/problems/stone-game-v/
