// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/825/F
// https://codeforces.com/problemset/status/825/problem/F?friends=on
func Test_cf825F(t *testing.T) {
	testCases := [][2]string{
		{
			`aaaaaaaaaa`,
			`3`,
		},
		{
			`abcab`,
			`6`,
		},
		{
			`cczabababab`,
			`7`,
		},
		{
			`abababcc`, // 写题解举例子，自测了一个数据，居然发现有 bug
			`5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf825F)
}
