// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/840/C 2500
// https://codeforces.com/problemset/status/840/problem/C?friends=on
func Test_cf840C(t *testing.T) {
	testCases := [][2]string{
		{
			`3
1 2 4`,
			`2`,
		},
		{
			`7
5 2 4 2 4 1 1`,
			`144`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf840C)
}
