// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/842/E 2800
// https://codeforces.com/problemset/status/842/problem/E?friends=on
func Test_cf842E(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1
1
2
1`,
			`2
2
2
3`,
		},
		{
			`4
1
1
2
3`,
			`2
2
2
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf842E)
}
