// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/868/F 2500
// https://codeforces.com/problemset/status/868/problem/F?friends=on
func Test_cf868F(t *testing.T) {
	testCases := [][2]string{
		{
			`7 3
1 1 3 3 3 2 1`,
			`1`,
		},
		{
			`10 2
1 2 1 2 1 2 1 2 1 2`,
			`8`,
		},
		{
			`13 3
1 2 2 2 1 2 1 1 1 2 2 1 1`,
			`9`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf868F)
}
