// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/870/C
// https://codeforces.com/problemset/status/870/problem/C
func Test_cf870C(t *testing.T) {
	testCases := [][2]string{
		{
			`1
12`,
			`3`,
		},
		{
			`2
6
8`,
			`1
2`,
		},
		{
			`3
1
2
3`,
			`-1
-1
-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf870C)
}
