// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/870/F 2700
// https://codeforces.com/problemset/status/870/problem/F?friends=on
func Test_cf870F(t *testing.T) {
	testCases := [][2]string{
		{
			`6`,
			`8`,
		},
		{
			`10`,
			`44`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf870F)
}
