// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/877/E
// https://codeforces.com/problemset/status/877/problem/E
func Test_cf877E(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1 1 1
1 0 0 1
9
get 1
get 2
get 3
get 4
pow 1
get 1
get 2
get 3
get 4`,
			`2
0
0
1
2
1
1
0`,
		},
		{
			`10
1 2 3 4 2 4 1 7 8
1 1 0 1 1 0 0 0 1 1
10
pow 1
get 2
pow 2
pow 8
get 6
pow 6
pow 10
get 6
pow 8
pow 3`,
			`3
0
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf877E)
}
