// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][3]string{
		{
			`["Constructor","Query","Query","Query","Query","Query","Query","Query","Query","Query","Query","Query","Query"]`,
			`[[["cd","f","kl"]],['a'],['b'],['c'],['d'],['e'],['f'],['g'],['h'],['i'],['j'],['k'],['l']]`,
			`[null,false,false,false,true,false,true,false,false,false,false,false,true]`,
		},
		// TODO 测试参数的下界和上界
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeClassWithExamples(t, Constructor, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-133/problems/stream-of-characters/
// 1032
