// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc438/tasks/abc438_d ~CF1204 652
// 提交：https://atcoder.jp/contests/abc438/submit?taskScreenName=abc438_d
// 对拍：https://atcoder.jp/contests/abc438/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc438_d&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc438/submissions?f.Status=AC&f.Task=abc438_d&orderBy=source_length
func Test_d(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1 4 2 4 3
2 3 4 2 2
3 2 4 4 3`,
			`16`,
		},
		{
			`3
1 1 1
1 1 1
1 1 1`,
			`3`,
		},
		{
			`6
2 10 7 7 7 11
5 7 9 10 9 12
6 6 7 10 12 7`,
			`50`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
