// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[[2,1,3],[6,1,4]]`, 
			`2`,
		},
		{
			`[[1,1,5],[10,10,5]]`, 
			`1`,
		},
		{
			`[[1,2,3],[2,3,1],[3,4,2],[4,5,3],[5,6,4]]`, 
			`5`,
		},
		{
			`[[4,4,3],[4,4,3]]`,
			`2`,
		},
	}
	targetCaseNum :=  -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, maximumDetonation, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-67/problems/detonate-the-maximum-bombs/
