// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[[2,1],[2,2],[3,3]]`, `90`, `[1,1]`, 
			`3`,
		},
		{
			`[[2,1],[2,2],[3,4],[1,1]]`, `90`, `[1,1]`, 
			`4`,
		},
		{
			`[[0,1],[2,1]]`, `13`, `[1,1]`, 
			`1`,
		},
		// TODO 测试参数的下界和上界
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, visiblePoints, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-209/problems/maximum-number-of-visible-points/
