// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2225/D 1500
// https://codeforces.com/problemset/status/2225/problem/D?friends=on
func Test_cf2225D(t *testing.T) {
	testCases := [][2]string{
		{
			`5
5 5
8 1
15 8
10 10
5989566119 1996588700`,
			`1
2
10
0
99996`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2225D)
}
