// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2242/D 1600
// https://codeforces.com/problemset/status/2242/problem/D?friends=on
func Test_cf2242D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
5147
44441
2194
5602
123450
012345`,
			`2
-1
5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2242D)
}
