// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2244/F 1700
// https://codeforces.com/problemset/status/2244/problem/F?friends=on
func Test_cf2244F(t *testing.T) {
	testCases := [][2]string{
		{
			`4
2
1
0 1
4
1 2 2
0 0 2 1
5
5 5 2 1
0 0 1 2 0
4
1 1 1
0 2 1 3`,
			`YES
YES
YES
NO`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2244F)
}
