// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2244/D 1200
// https://codeforces.com/problemset/status/2244/problem/D?friends=on
func Test_cf2244D(t *testing.T) {
	testCases := [][2]string{
		{
			`4
5 3
-1 2 -3 4 -5
1 5 3
4 2
3 -1 3 -1
4 2
3 1
-5 -5 -5
2
4 3
3 -1 1 -3
4 3 2`,
			`3
4
5
6`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2244D)
}
