// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2252/B 1100
// https://codeforces.com/problemset/status/2252/problem/B?friends=on
func Test_cf2252B(t *testing.T) {
	testCases := [][2]string{
		{
			`5
4
0101
3
111
6
100110
6
100010
6
011110`,
			`0
-1
2
3
5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2252B)
}
