// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[4,2,7,6,9,14,12]`, `5`, `1`, 
			`4`,
		},
		{
			`[4,12,2,7,3,18,20,3,19]`, `10`, `2`, 
			`7`,
		},
		{
			`[14,3,19,3]`, `17`, `0`, 
			`3`,
		},
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, furthestBuilding, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-213/problems/furthest-building-you-can-reach/
