// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1406/B
// https://codeforces.com/problemset/status/1406/problem/B?friends=on
func Test_cf1406B(t *testing.T) {
	testCases := [][2]string{
		{
			`4
5
-1 -2 -3 -4 -5
6
-1 -2 -3 1 2 -1
6
-1 0 0 0 -1 -1
6
-9 -7 -5 -3 -2 1`,
			`-120
12
0
945`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1406B)
}
