// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1413/D 1700
// https://codeforces.com/problemset/status/1413/problem/D?friends=on
func Test_cf1413D(t *testing.T) {
	testCases := [][2]string{
		{
			`4
+
+
- 2
+
- 3
+
- 1
- 4`,
			`YES
4 2 3 1`,
		},
		{
			`1
- 1
+`,
			`NO`,
		},
		{
			`3
+
+
+
- 2
- 1
- 3`,
			`NO`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1413D)
}
