// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1413/C 1900 2026.4.8
// https://codeforces.com/problemset/status/1413/problem/C?friends=on
func Test_cf1413C(t *testing.T) {
	testCases := [][2]string{
		{
			`1 4 100 10 30 5
6
101 104 105 110 130 200`,
			`0`,
		},
		{
			`1 1 2 2 3 3
7
13 4 11 12 11 13 12`,
			`7`,
		},
		{
			`11 16 12 20 12 13
10
21 21 21 21 21 21 21 21 21 21`,
			`0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1413C)
}
