// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1443/E
// https://codeforces.com/problemset/status/1443/problem/E?friends=on
func Test_cf1443E(t *testing.T) {
	testCases := [][2]string{
		{
			`4 4
1 2 4
2 3
1 1 2
1 3 4`,
			`9
4
6`,
		},
		{
			`50 2
2 97965
1 25 42`,
			`605`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1443E)
}
