// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1450/F 2400 2026.3.9
// https://codeforces.com/problemset/status/1450/problem/F?friends=on
func Test_cf1450F(t *testing.T) {
	testCases := [][2]string{
		{
			`4
6
2 1 2 3 1 1
5
1 1 1 2 2
8
7 7 2 7 7 1 8 7
10
1 2 3 4 1 1 2 3 4 1`,
			`1
3
-1
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1450F)
}
