// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1451/F 2700
// https://codeforces.com/problemset/status/1451/problem/F?friends=on
func Test_cf1451F(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1 1
0
1 3
0 0 5
2 2
0 1
1 0
3 3
1 2 3
4 5 6
7 8 9`,
			`Jeel
Ashish
Jeel
Ashish`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1451F)
}
