// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1473/B 1000
// https://codeforces.com/problemset/status/1473/problem/B?friends=on
func Test_cf1473B(t *testing.T) {
	testCases := [][2]string{
		{
			`3
baba
ba
aa
aaa
aba
ab`,
			`baba
aaaaaa
-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1473B)
}
