// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1474/E 2500
// https://codeforces.com/problemset/status/1474/problem/E?friends=on
func Test_cf1474E(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2
3
3`,
			`1
2 1
1
2 1
5
2 3 1
2
1 3
3 2
5
2 3 1
2
1 3
2 3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1474E)
}
