// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc339/tasks/abc339_e
// 提交：https://atcoder.jp/contests/abc339/submit?taskScreenName=abc339_e
// 对拍：https://atcoder.jp/contests/abc339/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc339_e&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc339/submissions?f.Status=AC&f.Task=abc339_e&orderBy=source_length
func Test_e(t *testing.T) {
	testCases := [][2]string{
		{
			`4 2
3 5 1 2`,
			`3`,
		},
		{
			`5 10
10 20 100 110 120`,
			`3`,
		},
		{
			`11 7
21 10 3 19 28 12 11 3 3 15 16`,
			`6`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
