// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1601/D 2700
// https://codeforces.com/problemset/status/1601/problem/D?friends=on
func Test_cf1601D(t *testing.T) {
	testCases := [][2]string{
		{
			`3 2
2 6
3 5
5 7`,
			`2`,
		},
		{
			`3 3
2 4
6 4
4 6`,
			`2`,
		},
		{
			`5 0
1 5
4 8
2 7
7 6
3 2`,
			`3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1601D)
}
