// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1612/G
// https://codeforces.com/problemset/status/1612/problem/G?friends=on
func Test_cf1612G(t *testing.T) {
	testCases := [][2]string{
		{
			`6
1 1 1 1 1 1`,
			`0 720`,
		},
		{
			`1
1000000`,
			`499833345 1`,
		},
		{
			`7
123 451 234 512 345 123 451`,
			`339854850 882811119`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1612G)
}
