// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1615/E 2400
// https://codeforces.com/problemset/status/1615/problem/E?friends=on
func Test_cf1615E(t *testing.T) {
	testCases := [][2]string{
		{
			`4 2
1 2
1 3
1 4`,
			`1`,
		},
		{
			`5 2
1 2
2 3
3 4
4 5`,
			`6`,
		},
		{
			`7 2
1 2
1 3
4 2
3 5
6 3
6 7`,
			`4`,
		},
		{
			`4 1
1 2
1 3
1 4`,
			`-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1615E)
}
