// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1621/F 2700 2026.4.27
// https://codeforces.com/problemset/status/1621/problem/F?friends=on
func Test_cf1621F(t *testing.T) {
	testCases := [][2]string{
		{
			`3
5 2 2 1
01101
6 4 3 5
110001
6 3 2 1
011110`,
			`3
11
4`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1621F)
}
