// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1626/F 2800
// https://codeforces.com/problemset/status/1626/problem/F?friends=on
func Test_cf1626F(t *testing.T) {
	testCases := [][2]string{
		{
			`3 10 3 5 13 88`,
			`382842030`,
		},
		{
			`2 15363 270880 34698 17 2357023`,
			`319392398`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1626F)
}
