// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1656/F
// https://codeforces.com/problemset/status/1656/problem/F?friends=on
func Test_cf1656F(t *testing.T) {
	testCases := [][2]string{
		{
			`5
2
1 0
2
-1 1
3
1 -1 -2
3
3 -1 -2
4
1 2 3 -4`,
			`INF
-1
INF
-6
-18`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1656F)
}
