// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1659/C
// https://codeforces.com/problemset/status/1659/problem/C
func Test_cf1659C(t *testing.T) {
	testCases := [][2]string{
		{
			`4
5 2 7
3 5 12 13 21
5 6 3
1 5 6 21 30
2 9 3
10 15
11 27182 31415
16 18 33 98 874 989 4848 20458 34365 38117 72030`,
			`173
171
75
3298918744`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1659C)
}
