// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1667/B 2100
// https://codeforces.com/problemset/status/1667/problem/B?friends=on
func Test_cf1667B(t *testing.T) {
	testCases := [][2]string{
		{
			`5
3
1 2 -3
4
0 -2 3 -4
5
-1 -2 3 -1 -1
6
-1 2 -3 4 -5 6
7
1 -1 -1 1 -1 -1 1`,
			`1
2
1
6
-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1667B)
}
