// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1673/C
// https://codeforces.com/problemset/status/1673/problem/C
func TestCF1673C(t *testing.T) {
	testCases := [][2]string{
		{
			`2
5
12`,
			`7
74`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, CF1673C)
}
