// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1677/D
// https://codeforces.com/problemset/status/1677/problem/D?friends=on
func Test_cf1677D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
5 0
0 1 2 3 4
5 2
-1 1 2 0 0
5 2
0 1 1 0 0`,
			`1
6
6`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1677D)
}
