// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1698/F 2800
// https://codeforces.com/problemset/status/1698/problem/F?friends=on
func Test_cf1698F(t *testing.T) {
	testCases := [][2]string{
		{
			`5
8
1 2 4 3 1 2 1 1
1 1 3 4 2 1 2 1
7
1 2 3 1 3 2 3
1 3 2 3 1 2 3
3
1 1 2
1 2 1
2
1 2
2 1
1
1
1`,
			`YES
2
5 8
1 6
YES
2
1 4
3 6
NO
NO
YES
0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1698F)
}
