// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`"10101"`, 
			`4`,
		},
		{
			`"1001"`, 
			`0`,
		},
		{
			`"0000"`, 
			`3`,
		},
		{
			`"100100010100110"`, 
			`12`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, numWays, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-34/problems/number-of-ways-to-split-a-string/
