// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/303/C 2400
// https://codeforces.com/problemset/status/303/problem/C?friends=on
func Test_cf303C(t *testing.T) {
	testCases := [][2]string{
		{
			`7 0
0 2 3 6 7 12 18`,
			`13`,
		},
		{
			`7 1
0 2 3 6 7 12 18`,
			`7`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf303C)
}
