// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/311/D 2600
// https://codeforces.com/problemset/status/311/problem/D?friends=on
func Test_cf311D(t *testing.T) {
	testCases := [][2]string{
		{
			`8
1 2 3 4 5 6 7 8
5
1 2 5
2 2 5
1 2 5
2 3 6
1 4 7`,
			`14
224
2215492`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf311D)
}
