// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/327/A
// https://codeforces.com/problemset/status/327/problem/A?friends=on
func Test_cf327A(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1 0 0 1 0`,
			`4`,
		},
		{
			`4
1 0 0 1`,
			`4`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf327A)
}
