// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/343/D
// https://codeforces.com/problemset/status/343/problem/D
func Test_cf343D(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1 2
5 1
2 3
4 2
12
1 1
2 3
3 1
3 2
3 3
3 4
1 2
2 4
3 1
3 3
3 4
3 5`,
			`0
0
0
1
0
1
0
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf343D)
}
