// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/351/C 2500
// https://codeforces.com/problemset/status/351/problem/C?friends=on
func Test_cf351C(t *testing.T) {
	testCases := [][2]string{
		{
			`2 6
1 2
2 1`,
			`12`,
		},
		{
			`1 10000000
2
3`,
			`25000000`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf351C)
}
