// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/385/B
// https://codeforces.com/problemset/status/385/problem/B?friends=on
func Test_cf385B(t *testing.T) {
	testCases := [][2]string{
		{
			`bearbtear`,
			`6`,
		},
		{
			`bearaabearc`,
			`20`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf385B)
}
