// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][3]string{
		{
			`["CombinationIterator","next","hasNext","next","hasNext","next","hasNext"]`,
			`[["abc",2],[],[],[],[],[],[]]`,
			`[null,"ab",true,"ac",true,"bc",false]`,
		},

	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeClassWithExamples(t, Constructor, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-15/problems/iterator-for-combination/
