// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`[3,2,1]`, `[0,3,3]`, `1`, `1`, 
			`3`,
		},
		{
			`[5,4]`, `[0,0,0]`, `1`, `5`, 
			`1`,
		},
		{
			`[10,15,30]`, `[0,10,10,10,10]`, `3`, `10`, 
			`2`,
		},
		{
			`[5,9,8,5,9]`, `[1,6,4,2,6]`, `1`, `5`, 
			`3`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, maxTaskAssign, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-65/problems/maximum-number-of-tasks-you-can-assign/
