// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`[0,1,1]`, 
			`[true,false,false]`,
		},
		{
			`[1,1,1]`, 
			`[false,false,false]`,
		},
		{
			`[0,1,1,1,1,1]`, 
			`[true,false,false,false,true,false]`,
		},
		{
			`[1,1,1,0,1]`, 
			`[false,false,false,false,false]`,
		},
		// TODO 测试参数的下界和上界
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, prefixesDivBy5, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-130/problems/binary-prefix-divisible-by-5/
