// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_a(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, minimumFlips, "a.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/biweekly-contest-170/problems/minimum-number-of-flips-to-reverse-binary-string/
// https://leetcode.cn/problems/minimum-number-of-flips-to-reverse-binary-string/
