// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`1`, `2`, `3`, 
			`2`,
		},
		{
			`4`, `2`, `3`, 
			`6`,
		},
		{
			`5`, `2`, `4`, 
			`10`,
		},
		{
			`3`, `6`, `4`, 
			`8`,
		},
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, nthMagicalNumber, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-95/problems/nth-magical-number/
