// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/arc120/submit?taskScreenName=arc120_c
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`3
3 1 4
6 2 0`,
			`2`,
		},
		{
			`3
1 1 1
1 1 2`,
			`-1`,
		},
		{
			`5
5 4 1 3 2
5 4 1 3 2`,
			`0`,
		},
		{
			`6
8 5 4 7 4 5
10 5 6 7 4 1`,
			`7`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/arc120/tasks/arc120_c
