// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/arc135/submit?taskScreenName=arc135_c
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`5
1 2 3 4 5`,
			`19`,
		},
		{
			`5
10 10 10 10 10`,
			`50`,
		},
		{
			`5
3 1 4 1 5`,
			`18`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/arc135/tasks/arc135_c
