// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc346/tasks/abc346_d
// 提交：https://atcoder.jp/contests/abc346/submit?taskScreenName=abc346_d
// 对拍：https://atcoder.jp/contests/abc346/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc346_d&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc346/submissions?f.Status=AC&f.Task=abc346_d&orderBy=source_length
func Test_d(t *testing.T) {
	testCases := [][2]string{
		{
			`5
00011
3 9 2 6 4`,
			`7`,
		},
		{
			`4
1001
1 2 3 4`,
			`0`,
		},
		{
			`11
11111100111
512298012 821282085 543342199 868532399 690830957 973970164 928915367 954764623 923012648 540375785 925723427`,
			`2286846953`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
