// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`[2,3,2]`, `2`, 
			`6`,
		},
		{
			`[5,1,1,1]`, `0`, 
			`8`,
		},
		{
			`[84,49,5,24,70,77,87,8]`, `3`,
			`154`,
		},
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, timeRequiredToBuy, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-267/problems/time-needed-to-buy-tickets/
