// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P3292
func Test_p3292(t *testing.T) {
	testCases := [][2]string{
		{
			`4 2
11 5 7 9
1 2
1 3
1 4
2 3
1 4`,
			`14 
11`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p3292)
}
