// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P3522
func Test_p3522(t *testing.T) {
	testCases := [][2]string{
		{
			`6
6 10
1 5
4 8
2 5
6 8
3 5`,
			`4`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p3522)
}
