// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P3694
func Test_p3694(t *testing.T) {
	testCases := [][2]string{
		{
			`12 4
1
3
2
4
2
1
2
3
1
1
3
4`,
			`7`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p3694)
}
