// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	examples := [][]string{
		{
			`[2,5]`, `[3,4]`, `2`, 
			`8`,
		},
		{
			`[-4,-2,0,3]`, `[2,4]`, `6`, 
			`0`,
		},
		{
			`[-2,-1,0,1,2]`, `[-3,-1,2,4,5]`, `3`, 
			`-6`,
		},
		{
			`[-9,6,10]`, `[-7,-1,1,2,3,4,4,6,9,10]`, `15`,
			`10`,
		},
		{
			`[1,6]`, `[-10,-10,-5,-4,-3,-1]`, `9`,
			`-5`,
		},
	}
	if err := testutil.RunLeetCodeFuncWithExamples(t, kthSmallestProduct, examples, 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-63/problems/kth-smallest-product-of-two-sorted-arrays/
