// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_a(t *testing.T) {
	examples := [][]string{
		{
			`[1,2,3]`, 
			`5`,
		},
		{
			`[6,5,7,9,2,2]`, 
			`23`,
		},
		{
			`[5,5]`, 
			`10`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, minimumCost, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-70/problems/minimum-cost-of-buying-candies-with-discount/
