// Code generated by copypasta/template/acwing/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`3 7
4 5 14`,
			`4`,
		},
		{
			`6 1
1 1 1 1 1 1`,
			`6`,
		},
		{
			`6 5
7 6 8 9 10 5`,
			`11`,
		},
	}
	target := 0 // -1
	testutil.AssertEqualStringCase(t, testCases, target, run)
}
