// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_d(t *testing.T) {
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithFile(t, minCost, "d.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-331/problems/rearranging-fruits/

//func TestCompareInf(_t *testing.T) {
//	testutil.DebugTLE = 0
//
//	inputGenerator := func() (a,b []int) {
//		//return
//		return
//		rg := testutil2.NewRandGenerator()
//		n := rg.Int(1, 99)
//		a = rg.IntSlice(n, 1, 99)
//		b = rg.IntSlice(n, 1, 99)
//		return
//	}
//
//	testutil.CompareInf(_t, inputGenerator, minCostAC, minCost)
//}
