// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc359/tasks/abc359_d
// 提交：https://atcoder.jp/contests/abc359/submit?taskScreenName=abc359_d
// 对拍：https://atcoder.jp/contests/abc359/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc359_d&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc359/submissions?f.Status=AC&f.Task=abc359_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`7 4
AB?A?BA`,
			`1`,
		},
		{
			`40 7
????????????????????????????????????????`,
			`116295436`,
		},
		{
			`15 5
ABABA??????????`,
			`0`,
		},
		{
			`40 8
?A?B??B?B?AA?A?B??B?A???B?BB?B???BA??BAA`,
			`259240`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
