// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_c(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, maximumSum, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-505/problems/maximum-sum-of-m-non-overlapping-subarrays-i/
// https://leetcode.cn/problems/maximum-sum-of-m-non-overlapping-subarrays-i/
