// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc397/tasks/abc397_f ~CF2037 1753
// 提交：https://atcoder.jp/contests/abc397/submit?taskScreenName=abc397_f
// 对拍：https://atcoder.jp/contests/abc397/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc397_f&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc397/submissions?f.Status=AC&f.Task=abc397_f&orderBy=source_length
func Test_f(t *testing.T) {
	testCases := [][2]string{
		{
			`5
3 1 4 1 5`,
			`5`,
		},
		{
			`10
2 5 6 4 4 1 1 3 1 4`,
			`9`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
