// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`[1,3,4,8]`, `[[0,1],[1,2],[2,3],[0,3]]`, 
			`[2,1,4,1]`,
		},
		{
			`[4,5,2,2,7,10]`, `[[2,3],[0,2],[0,5],[3,5]]`, 
			`[-1,1,1,3]`,
		},
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, minDifference, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-246/problems/minimum-absolute-difference-queries/
