// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_c(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, minJumps, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-460/problems/minimum-jumps-to-reach-end-via-prime-teleportation/
// https://leetcode.cn/problems/minimum-jumps-to-reach-end-via-prime-teleportation/
