// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	exampleIns := [][]string{{`[1,0,1,0]`, `[7,5,4,100]`, `[[],[],[1],[]]`, `[[1,2],[3],[],[]]`, `[0]`}, {`[1,0,0,0,0,0]`, `[1,1,1,1,1,1]`, `[[1,2,3,4,5],[],[],[],[],[]]`, `[[1,2,3,4,5],[],[],[],[],[]]`, `[0]`}, {`[1,1,1]`, `[100,1,100]`, `[[],[0,2],[]]`, `[[],[],[]]`, `[1]`}, {`[1]`, `[100]`, `[[]]`, `[[]]`, `[]`}, {`[1,1,1]`, `[2,3,2]`, `[[],[],[]]`, `[[],[],[]]`, `[2,1,0]`}}
	exampleOuts := [][]string{{`16`}, {`6`}, {`1`}, {`0`}, {`7`}}
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	if err := testutil.RunLeetCodeFunc(t, maxCandies, exampleIns, exampleOuts); err != nil {
		t.Fatal(err)
	}
}
