// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`["acca","bbbb","caca"]`, `"aba"`, 
			`6`,
		},
		{
			`["abba","baab"]`, `"bab"`, 
			`4`,
		},
		{
			`["abcd"]`, `"abcd"`, 
			`1`,
		},
		{
			`["abab","baba","abba","baab"]`, `"abba"`, 
			`16`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, numWays, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-38/problems/number-of-ways-to-form-a-target-string-given-a-dictionary/
