// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`4`, `[1,3,1,2]`, 
			`[1,2]`,
		},
		{
			`2`, `[2,1,2,1,2,1,2,1,2]`, 
			`[2]`,
		},
		{
			`7`, `[1,3,5,7]`, 
			`[1,2,3,4,5,6,7]`,
		},
		// TODO 测试参数的下界和上界
		{
			`10`, `[5,2]`,
			`[1,2]`,
		},
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, mostVisited, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-203/problems/most-visited-sector-in-a-circular-track/
