// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[1,1,2,1,3,2,2,3,3]`, `[[1,3],[2,2],[6,1]]`, 
			`[3,0,3]`,
		},
		{
			`[1,2]`, `[[0,3]]`, 
			`[-1]`,
		},
		// TODO 测试入参最小的情况
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, shortestDistanceColor, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-8/problems/shortest-distance-to-target-color/
