// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[[1,2],[2,4],[3,2],[4,1]]`, 
			`[0,2,3,1]`,
		},
		{
			`[[7,10],[7,12],[7,5],[7,4],[7,2]]`, 
			`[4,3,2,0,1]`,
		},
		// TODO 测试入参最小的情况
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, getOrder, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-237/problems/single-threaded-cpu/
