// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`["E23","2X2","12S"]`, 
			`[7,1]`,
		},
		{
			`["E12","1X1","21S"]`, 
			`[4,2]`,
		},
		{
			`["E11","XXX","11S"]`, 
			`[0,0]`,
		},
		
	}
	targetCaseNum := 3
	if err := testutil.RunLeetCodeFuncWithExamples(t, pathsWithMaxScore, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-16/problems/number-of-paths-with-max-score/
