// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/practice2/tasks/practice2_j
// 提交：https://atcoder.jp/contests/practice2/submit?taskScreenName=practice2_j
// 对拍：https://atcoder.jp/contests/practice2/submissions?f.LanguageName=Go&f.Status=AC&f.Task=practice2_j&orderBy=source_length
// 最短：https://atcoder.jp/contests/practice2/submissions?f.Status=AC&f.Task=practice2_j&orderBy=source_length
func Test_j(t *testing.T) {
	testCases := [][2]string{
		{
			`5 5
1 2 3 2 1
2 1 5
3 2 3
1 3 1
2 2 4
3 1 3`,
			`3
3
2
6`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
