// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	exampleIns := [][]string{{`[4,2,1,3]`}, {`[1,3,6,10,15]`}, {`[3,8,-10,23,19,-4,-14,27]`}}
	exampleOuts := [][]string{{`[[1,2],[2,3],[3,4]]`}, {`[[1,3]]`}, {`[[-14,-10],[19,23],[23,27]]`}}
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	if err := testutil.RunLeetCodeFunc(t, minimumAbsDifference, exampleIns, exampleOuts); err != nil {
		t.Fatal(err)
	}
}
