// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`[["a"],["c"],["d"],["a","b"],["c","b"],["d","a"]]`, 
			`[["d"],["d","a"]]`,
		},
		{
			`[["a"],["c"],["a","b"],["c","b"],["a","b","x"],["a","b","x","y"],["w"],["w","y"]]`, 
			`[["c"],["c","b"],["a"],["a","b"]]`,
		},
		{
			`[["a","b"],["c","d"],["c"],["a"]]`, 
			`[["c"],["c","d"],["a"],["a","b"]]`,
		},
		{
			`[["a"],["a","x"],["a","x","y"],["a","z"],["b"],["b","x"],["b","x","y"],["b","z"]]`, 
			`[]`,
		},
		{
			`[["a"],["a","x"],["a","x","y"],["a","z"],["b"],["b","x"],["b","x","y"],["b","z"],["b","w"]]`, 
			`[["b"],["b","w"],["b","z"],["a"],["a","z"]]`,
		},
		
	}
	targetCaseNum :=1
	if err := testutil.RunLeetCodeFuncWithExamples(t, deleteDuplicateFolder, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-251/problems/delete-duplicate-folders-in-system/
