// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/212/E
// https://codeforces.com/problemset/status/212/problem/E?friends=on
func Test_cf212E(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1 2
2 3
3 4
4 5`,
			`3
1 3
2 2
3 1`,
		},
		{
			`10
1 2
2 3
3 4
5 6
6 7
7 4
8 9
9 10
10 4`,
			`6
1 8
2 7
3 6
6 3
7 2
8 1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf212E)
}
