// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/220/E
// https://codeforces.com/problemset/status/220/problem/E?friends=on
func Test_cf220E(t *testing.T) {
	testCases := [][2]string{
		{
			`3 1
1 3 2`,
			`3`,
		},
		{
			`5 2
1 3 2 1 7`,
			`6`,
		},
		{
			`7 3
1 7 6 4 9 5 3`,
			`6`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf220E)
}
