// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/233/B 1400
// https://codeforces.com/problemset/status/233/problem/B?friends=on
func Test_cf233B(t *testing.T) {
	testCases := [][2]string{
		{
			`2`,
			`1`,
		},
		{
			`110`,
			`10`,
		},
		{
			`4`,
			`-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf233B)
}
