// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/240/F
// https://codeforces.com/problemset/status/240/problem/F
func Test_cf240F(t *testing.T) {
	testCases := [][2]string{
		{
			`7 2
aabcbaa
1 3
5 7`,
			`abacaba`,
		},
		{
			`3 2
abc
1 2
2 3`,
			`abc`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf240F)
}
