// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/241/E 2600
// https://codeforces.com/problemset/status/241/problem/E?friends=on
func Test_cf241E(t *testing.T) {
	testCases := [][2]string{
		{
			`3 3
1 2
2 3
1 3`,
			`Yes
1
1
2`,
		},
		{
			`4 4
1 2
2 3
3 4
1 4`,
			`No`,
		},
		{
			`5 6
1 2
2 3
3 5
1 4
4 5
1 3`,
			`Yes
1
1
1
2
1
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf241E)
}
