// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/283/D 2400
// https://codeforces.com/problemset/status/283/problem/D?friends=on
func Test_cf283D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
6 4 1`,
			`0`,
		},
		{
			`4
20 6 3 4`,
			`2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf283D)
}
