// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/294/E
// https://codeforces.com/problemset/status/294/problem/E?friends=on
func Test_cf294E(t *testing.T) {
	testCases := [][2]string{
		{
			`3
1 2 2
1 3 4`,
			`12`,
		},
		{
			`6
1 2 1
2 3 1
3 4 1
4 5 1
5 6 1`,
			`29`,
		},
		{
			`6
1 3 1
2 3 1
3 4 100
4 5 2
4 6 1`,
			`825`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf294E)
}
