// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[[2,5,3],[1,8,4],[1,7,5]]`, `[2,7,5]`, 
			`true`,
		},
		{
			`[[1,3,4],[2,5,8]]`, `[2,5,8]`, 
			`true`,
		},
		{
			`[[2,5,3],[2,3,4],[1,2,5],[5,2,3]]`, `[5,5,5]`, 
			`true`,
		},
		{
			`[[3,4,5],[4,5,6]]`, `[3,2,5]`, 
			`false`,
		},
		// TODO 测试入参最小的情况
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, mergeTriplets, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-245/problems/merge-triplets-to-form-target-triplet/
