// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [d]")
	examples := [][]string{
		{
			`[2,4,5,8,10]`, `[4,6,8,9]`, 
			`30`,
		},
		{
			`[1,3,5,7,9]`, `[3,5,100]`, 
			`109`,
		},
		{
			`[1,2,3,4,5]`, `[6,7,8,9,10]`, 
			`40`,
		},
		{
			`[1,4,5,8,9,11,19]`, `[2,3,4,11,12]`, 
			`61`,
		},
		// TODO 测试参数的下界和上界
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, maxSum, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-200/problems/get-the-maximum-score/
