// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	exampleIns := [][]string{{`"URR"`, `[]`, `3`, `2`}, {`"URR"`, `[[2, 2]]`, `3`, `2`}, {`"URR"`, `[[4, 2]]`, `3`, `2`}}
	exampleOuts := [][]string{{`true`}, {`false`}, {`true`}}
	// TODO: 测试参数的下界和上界！
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithCase(t, robot, exampleIns, exampleOuts, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/season/2019-fall/problems/programmable-robot/
