// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc253/tasks/abc253_f
// 提交：https://atcoder.jp/contests/abc253/submit?taskScreenName=abc253_f
// 对拍：https://atcoder.jp/contests/abc253/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc253_f&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc253/submissions?f.Status=AC&f.Task=abc253_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`3 3 9
1 1 2 1
3 2 2
2 3 2
3 3 3
3 3 1
1 2 3 3
3 3 2
3 2 3
3 1 2`,
			`1
2
2
5
3
4`,
		},
		{
			`1 1 10
1 1 1 1000000000
1 1 1 1000000000
1 1 1 1000000000
1 1 1 1000000000
1 1 1 1000000000
1 1 1 1000000000
1 1 1 1000000000
1 1 1 1000000000
1 1 1 1000000000
3 1 1`,
			`9000000000`,
		},
		{
			`10 10 10
1 1 8 5
2 2 6
3 2 1
3 4 7
1 5 9 7
3 3 2
3 2 8
2 8 10
3 8 8
3 1 10`,
			`6
5
5
13
10
0`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
