// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[1,3]`, `6`, `4`, 
			`2`,
		},
		{
			`[2,4,12]`, `2`, `12`, 
			`2`,
		},
		{
			`[3,5,7]`, `0`, `-4`, 
			`2`,
		},
		{
			`[2,8,16]`, `0`, `1`, 
			`-1`,
		},
		{
			`[1]`, `0`, `3`, 
			`3`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, minimumOperations, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-265/problems/minimum-operations-to-convert-number/
