// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`"LeetcodeHelpsMeLearn"`, `[8,13,15]`, 
			`"Leetcode Helps Me Learn"`,
		},
		{
			`"icodeinpython"`, `[1,5,7,9]`, 
			`"i code in py thon"`,
		},
		{
			`"spacing"`, `[0,1,2,3,4,5,6]`, 
			`" s p a c i n g"`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, addSpaces, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-272/problems/adding-spaces-to-a-string/
