// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/arc119/submit?taskScreenName=arc119_b
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`7
1110110
1010111`,
			`2`,
		},
		{
			`20
11111000000000011111
11111000000000011111`,
			`0`,
		},
		{
			`6
111100
111000`,
			`-1`,
		},
		{
			`119
10101111011101001011111000111111101011110011010111111111111111010111111111111110111111110111110111101111111111110111011
11111111111111111111111111011111101011111011110111110010100101001110111011110111111111110010011111101111111101110111011`,
			`22`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/arc119/tasks/arc119_b
