// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[1,2,3,null,4]`, `3`, 
			`1`,
		},
		{
			`[1,2,3,4,5,6,7]`, `3`, 
			`2`,
		},
		{
			`[7,1,4,6,null,5,3,null,null,null,null,null,2]`, `3`, 
			`1`,
		},
		{
			`[100]`, `1`, 
			`0`,
		},
		{
			`[1,1,1]`, `2`, 
			`1`,
		},
		// TODO 测试参数的下界和上界
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, countPairs, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-199/problems/number-of-good-leaf-nodes-pairs/
