// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	exampleIns := [][]string{{`"HOW ARE YOU"`}, {`"TO BE OR NOT TO BE"`}, {`"CONTEST IS COMING"`}}
	exampleOuts := [][]string{{`["HAY","ORO","WEU"]`}, {`["TBONTB","OEROOE","   T"]`}, {`["CIC","OSO","N M","T I","E N","S G","T"]`}}
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	if err := testutil.RunLeetCodeFunc(t, printVertically, exampleIns, exampleOuts); err != nil {
		t.Fatal(err)
	}
}
