// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_c(t *testing.T) {
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithFile(t, maxMoves, "c.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
	if err := testutil.RunFuncWithRandomInput(t, maxMoves); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-345/problems/maximum-number-of-moves-in-a-grid/
// https://leetcode.cn/problems/maximum-number-of-moves-in-a-grid/
