// Code generated by copypasta/template/nowcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`5`,
			`3`,
		},
		// TODO 测试参数的下界和上界
		{
			`1`,
			`1`,
		},
		{
			`2`,
			`2`,
		},
		{
			`3`,
			`2`,
		},
		{
			`4`,
			`3`,
		},
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, stick, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://ac.nowcoder.com/acm/contest/9224/a
