// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`["bread"]`, `[["yeast","flour"]]`, `["yeast","flour","corn"]`, 
			`["bread"]`,
		},
		{
			`["bread","sandwich"]`, `[["yeast","flour"],["bread","meat"]]`, `["yeast","flour","meat"]`, 
			`["bread","sandwich"]`,
		},
		{
			`["bread","sandwich","burger"]`, `[["yeast","flour"],["bread","meat"],["sandwich","meat","bread"]]`, `["yeast","flour","meat"]`, 
			`["bread","sandwich","burger"]`,
		},
		{
			`["bread"]`, `[["yeast","flour"]]`, `["yeast"]`, 
			`[]`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, findAllRecipes, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-68/problems/find-all-possible-recipes-from-given-supplies/
