// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`[-1,-2,-3,-4,3,2,1]`, 
			`1`,
		},
		{
			`[1,5,0,2,-3]`, 
			`0`,
		},
		{
			`[-1,1,-1,1,-1]`, 
			`-1`,
		},
		// TODO 测试入参最小的情况
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, arraySign, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-236/problems/sign-of-the-product-of-an-array/
