// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/arc072/submit?taskScreenName=arc072_a
func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`4
1 -3 1 0`,
			`4`,
		},
		{
			`5
3 -6 4 -5 7`,
			`0`,
		},
		{
			`6
-1 4 3 2 -5 4`,
			`8`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/abc059/tasks/arc072_a
