// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	. "fmt"
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"io"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc346/tasks/abc346_g ~CF2349 2166
// 提交：https://atcoder.jp/contests/abc346/submit?taskScreenName=abc346_g
// 对拍：https://atcoder.jp/contests/abc346/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc346_g&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc346/submissions?f.Status=AC&f.Task=abc346_g&orderBy=source_length
func Test_g(t *testing.T) {
	testCases := [][2]string{
		{
			`5
2 2 1 2 1`,
			`12`,
		},
		{
			`4
4 4 4 4`,
			`4`,
		},
		{
			`10
1 2 1 4 3 3 3 2 2 4`,
			`47`,
		},
		{
			`4
1 2 1 2`,
			`9`,
		},
		{
			`3
1 3 3`,
			`5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}

func TestCompare(_t *testing.T) {
	return
	testutil.DebugTLE = 0
	rg := testutil.NewRandGenerator()
	inputGenerator := func() string {
		rg.Clear()
		n := rg.Int(1, 7)
		rg.NewLine()
		rg.IntSlice(n, 1, n)
		return rg.String()
	}

	// 暴力算法
	runBF := func(in io.Reader, out io.Writer) {
		var n, ans int
		Fscan(in, &n)
		a := make([]int, n)
		for i := range a {
			Fscan(in, &a[i])
		}
		for l := range a {
			cnt := map[int]int{}
			for r := l; r < len(a); r++ {
				v := a[r]
				cnt[v]++
				for _, c := range cnt {
					if c == 1 {
						ans++
						break
					}
				}
			}
		}
		Fprintln(out, ans)
	}

	testutil.AssertEqualRunResultsInf(_t, inputGenerator, runBF, run)
}
