// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc253/tasks/abc253_e
// 提交：https://atcoder.jp/contests/abc253/submit?taskScreenName=abc253_e
// 对拍：https://atcoder.jp/contests/abc253/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc253_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`2 3 1`,
			`6`,
		},
		{
			`3 3 2`,
			`2`,
		},
		{
			`100 1000 500`,
			`657064711`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
