// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`2
1 2
2 3`,
			`3`,
		},
		{
			`3
100 100
10 10000
1 1000000000`,
			`9991`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
	//testutil.AssertEqualRunResults(t, testCases, 0, runAC, run)
}
// https://atcoder.jp/contests/abc169/tasks/abc169_e
// https://atcoder.jp/contests/abc169/submit?taskScreenName=abc169_e
