// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	exampleIns := [][]string{{`[["A","B"],["C"],["B","C"],["D"]]`, `[[1,2],[0,3],[0,3],[1,2]]`, `0`, `1`}, {`[["A","B"],["C"],["B","C"],["D"]]`, `[[1,2],[0,3],[0,3],[1,2]]`, `0`, `2`}}
	exampleOuts := [][]string{{`["B","C"]`}, {`["D"]`}}
	// custom test cases or WA cases.
	//exampleIns = append(exampleIns, []string{``})
	//exampleOuts = append(exampleOuts, []string{``})
	if err := testutil.RunLeetCodeFunc(t, watchedVideosByFriends, exampleIns, exampleOuts); err != nil {
		t.Fatal(err)
	}
}
