// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_b(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, removeDuplicates, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-137/problems/remove-all-adjacent-duplicates-in-string/
// https://leetcode.cn/problems/remove-all-adjacent-duplicates-in-string/
