// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`[1,2,3,4,5,10,6,7,8,9]`, `5`, 
			`true`,
		},
		{
			`[1,2,3,4,5,6]`, `7`, 
			`true`,
		},
		{
			`[1,2,3,4,5,6]`, `10`, 
			`false`,
		},
		{
			`[-10,10]`, `2`, 
			`true`,
		},
		{
			`[-1,1,-2,2,-3,3,-4,4]`, `3`, 
			`true`,
		},
		// TODO 测试参数的下界和上界
		
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, canArrange, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-195/problems/check-if-array-pairs-are-divisible-by-k/
