// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1511/G 2700
// https://codeforces.com/problemset/status/1511/problem/G?friends=on
func Test_cf1511G(t *testing.T) {
	testCases := [][2]string{
		{
			`8 10
1 3 3 7 4 2 6 9
7
2 3
1 3
1 4
1 10
5 10
8 10
9 10`,
			`BAAAAAB`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1511G)
}
