// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1530/D
// https://codeforces.com/problemset/status/1530/problem/D
func Test_cf1530D(t *testing.T) {
	testCases := [][2]string{
		{
			`2
3
2 1 2
7
6 4 6 2 4 5 6`,
			`2
3 1 2
4
6 4 7 2 3 5 1`,
		},
		{
			`1
6
4 3 2 3 3 5`,
			`4
4 3 2 6 1 5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1530D)
}
