// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1538/C
// https://codeforces.com/problemset/status/1538/problem/C
func Test_cf1538C(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3 4 7
5 1 2
5 5 8
5 1 2 4 3
4 100 1000
1 1 1 1
5 9 13
2 5 5 1 1`,
			`2
7
0
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1538C)
}
