// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1574/B 1100
// https://codeforces.com/problemset/status/1574/problem/B?friends=on
func Test_cf1574B(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2 2 1 0
1 1 1 1
1 2 3 2`,
			`YES
NO
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1574B)
}
