// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1575/L 2100 2026.5.3
// https://codeforces.com/problemset/status/1575/problem/L?friends=on
func Test_cf1575L(t *testing.T) {
	testCases := [][2]string{
		{
			`7
2 1 4 2 5 3 7`,
			`3`,
		},
		{
			`4
4 2 3 1`,
			`2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1575L)
}
