// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1580/B
// https://codeforces.com/problemset/status/1580/problem/B?friends=on
func Test_cf1580B(t *testing.T) {
	testCases := [][2]string{
		{
			`4 3 2 10007`,
			`4`,
		},
		{
			`6 4 1 769626776`,
			`472`,
		},
		{
			`66 11 9 786747482`,
			`206331312`,
		},
		{
			`99 30 18 650457567`,
			`77365367`,
		},
		{
			`100 100 100 905987364`,
			`0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1580B)
}
