// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1582/G 2600
// https://codeforces.com/problemset/status/1582/problem/G?friends=on
func Test_cf1582G(t *testing.T) {
	testCases := [][2]string{
		{
			`3
1 2 3
*/*`,
			`2`,
		},
		{
			`7
6 4 10 1 2 15 1
*/*/*//`,
			`8`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1582G)
}
