// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1582/D
// https://codeforces.com/problemset/status/1582/problem/D
func Test_cf1582D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2
5 5
5
5 -2 10 -9 4
7
1 2 3 4 5 6 7`,
			`1 -1
-1 5 1 -1 -1
-10 2 2 -3 5 -1 -1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1582D)
}
