// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1583/F 2500
// https://codeforces.com/problemset/status/1583/problem/F?friends=on
func Test_cf1583F(t *testing.T) {
	testCases := [][2]string{
		{
			`5 3`,
			`2
1 2 2 2 2 2 2 1 1 1`,
		},
		{
			`5 2`,
			`3
3 2 2 1 2 2 1 3 1 1`,
		},
		{
			`8 7`,
			`2
2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1`,
		},
		{
			`3 2`,
			`2
1 2 2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1583F)
}
