// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1585/F 2400
// https://codeforces.com/problemset/status/1585/problem/F?friends=on
func Test_cf1585F(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2 2 2`,
			`2`,
		},
		{
			`2
2 3`,
			`4`,
		},
		{
			`3
1 1 1`,
			`0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1585F)
}
