// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1592/E
// https://codeforces.com/problemset/status/1592/problem/E?friends=on
func Test_cf1592E(t *testing.T) {
	testCases := [][2]string{
		{
			`2
5 6`,
			`2`,
		},
		{
			`3
2 4 3`,
			`0`,
		},
		{
			`6
8 1 3 3 1 2`,
			`4`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1592E)
}
