// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1598/F 2400
// https://codeforces.com/problemset/status/1598/problem/F?friends=on
func Test_cf1598F(t *testing.T) {
	testCases := [][2]string{
		{
			`2
(
)`,
			`1`,
		},
		{
			`4
()()())
(
(
)`,
			`4`,
		},
		{
			`1
(())`,
			`1`,
		},
		{
			`1
)(()`,
			`0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1598F)
}
