// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`[[1,3,2],[4,5,2],[2,4,3]]`, 
			`4`,
		},
		{
			`[[1,3,2],[4,5,2],[1,5,5]]`, 
			`5`,
		},
		{
			`[[1,5,3],[1,5,1],[6,6,5]]`, 
			`8`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, maxTwoEvents, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-64/problems/two-best-non-overlapping-events/
