// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`7`, `[-1,0,0,1,2,2,2]`, `[1,-2,4,0,-2,-1,-1]`, 
			`2`,
		},
		{
			`7`, `[-1,0,0,1,2,2,2]`, `[1,-2,4,0,-2,-1,-2]`, 
			`6`,
		},
		{
			`5`, `[-1,0,1,0,0]`, `[-672,441,18,728,378]`, 
			`5`,
		},
		{
			`5`, `[-1,0,0,1,1]`, `[-686,-842,616,-739,-746]`, 
			`5`,
		},
		// TODO 测试入参最小的情况
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, deleteTreeNodes, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-14/problems/delete-tree-nodes/
