// Code generated by copypasta/template/nowcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`4`,`[1,2,5,6,2]`,
			`[48,138,274,410,510]`,
		},
		// TODO 测试参数的下界和上界
		{
			`1`,`[1,2,1,3,4,5,6]`,
			`[1,2,3,4,5,6,7]`,
		},
		{
			`2`,`[1,1]`,
			`[1]`,
		},
	}
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithExamples(t, getScores, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://ac.nowcoder.com/acm/contest/6489/c
