// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc342/tasks/abc342_d
// 提交：https://atcoder.jp/contests/abc342/submit?taskScreenName=abc342_d
// 对拍：https://atcoder.jp/contests/abc342/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc342_d&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc342/submissions?f.Status=AC&f.Task=abc342_d&orderBy=source_length
func Test_d(t *testing.T) {
	testCases := [][2]string{
		{
			`5
0 3 2 8 12`,
			`6`,
		},
		{
			`8
2 2 4 6 3 100 100 25`,
			`7`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
