// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	exampleIns := [][]string{{`[[1,2],[2,3],[3,4],[4,5],[5,6],[6,7]]`}, {`[[1,1],[2,2],[3,4],[4,5],[5,6],[7,7]]`}}
	exampleOuts := [][]string{{`true`}, {`false`}}
	// TODO: 测试参数的下界和上界！
	// custom test cases or WA cases.
	exampleIns = append(exampleIns, []string{`[[-3,-2],[-1,-2],[2,-2],[-2,-2],[0,-2]]`})
	exampleOuts = append(exampleOuts, []string{`true`})
	const targetCaseNum = 3
	if err := testutil.RunLeetCodeFuncWithCase(t, checkStraightLine, exampleIns, exampleOuts, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
