// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_a(t *testing.T) {
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithFile(t, minLength, "a.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
	if err := testutil.RunFuncWithRandomInput(t, minLength); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-346/problems/minimum-string-length-after-removing-substrings/
// https://leetcode.cn/problems/minimum-string-length-after-removing-substrings/
