// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://www.luogu.com.cn/problem/P2617
func Test_p2617(t *testing.T) {
	testCases := [][2]string{
		{
			`5 3
3 2 1 4 7
Q 1 4 3
C 2 6
Q 2 5 3`,
			`3
6`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, p2617)
}
