// Code generated by generator_test.
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

// 1e9~1e18 √n logn 1     二分 二进制
// 1e5~1e6  nlogn nαn n   二分 RMQ 并查集
// 1e3~1e4  n^2 n√n       RMQ DP 分块
// 300~500  n^3           DP 二分图
func Test(t *testing.T) {
	t.Log("Current test is [d]")
	exampleIns := [][]string{{`[9,3,5]`}, {`[1,1,1,2]`}, {`[8,5]`}}
	exampleOuts := [][]string{{`true`}, {`false`}, {`true`}}
	// TODO: 测试参数的下界和上界！
	// custom test cases or WA cases.
	exampleIns = append(exampleIns, []string{`[2]`})
	exampleOuts = append(exampleOuts, []string{`false`})
	targetCaseNum := 0
	if err := testutil.RunLeetCodeFuncWithCase(t, isPossible, exampleIns, exampleOuts, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-176/problems/construct-target-array-with-multiple-sums/
