// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [a]")
	examples := [][]string{
		{
			`["leetcode","is","amazing","as","is"]`, `["amazing","leetcode","is"]`, 
			`2`,
		},
		{
			`["b","bb","bbb"]`, `["a","aa","aaa"]`, 
			`0`,
		},
		{
			`["a","ab"]`, `["a","a","a","ab"]`, 
			`1`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, countWords, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-66/problems/count-common-words-with-one-occurrence/
