// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/10/C
// https://codeforces.com/problemset/status/10/problem/C
func TestCF10C(t *testing.T) {
	testCases := [][2]string{
		{
			`4`,
			`2`,
		},
		{
			`5`,
			`6`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, CF10C)
}
