// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/17/D 2400
// https://codeforces.com/problemset/status/17/problem/D?friends=on
func Test_cf17D(t *testing.T) {
	testCases := [][2]string{
		{
			`2 3 3`,
			`1`,
		},
		{
			`2 3 4`,
			`4`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf17D)
}
