// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/27/E
// https://codeforces.com/problemset/status/27/problem/E
func Test_cf27E(t *testing.T) {
	testCases := [][2]string{
		{
			`4`,
			`6`,
		},
		{
			`6`,
			`12`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf27E)
}
