// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/33/B
// https://codeforces.com/problemset/status/33/problem/B
func Test_cf33B(t *testing.T) {
	testCases := [][2]string{
		{
			`uayd
uxxd
3
a x 8
x y 13
d c 3`,
			`21
uxyd`,
		},
		{
			`a
b
3
a b 2
a b 3
b a 5`,
			`2
b`,
		},
		{
			`abc
ab
6
a b 4
a b 7
b a 8
c b 11
c a 3
a c 0`,
			`-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf33B)
}
