// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/67/C 2600
// https://codeforces.com/problemset/status/67/problem/C?friends=on
func Test_cf67C(t *testing.T) {
	testCases := [][2]string{
		{
			`1 1 1 1
youshouldnot
thoushaltnot`,
			`5`,
		},
		{
			`2 4 10 3
ab
ba`,
			`3`,
		},
		{
			`1 10 20 30
a
za`,
			`1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf67C)
}
