// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/67/D
// https://codeforces.com/problemset/status/67/problem/D
func Test_cf67D(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1 4 5 2 3
3 4 2 1 5`,
			`3`,
		},
		{
			`3
3 1 2
2 3 1`,
			`2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf67D)
}
