// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/68/D 2500
// https://codeforces.com/problemset/status/68/problem/D?friends=on
func Test_cf68D(t *testing.T) {
	testCases := [][2]string{
		{
			`1 4
add 1 3
add 2 10
add 3 11
decay`,
			`13.50000000`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf68D)
}
