// Code generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/69/E
// https://codeforces.com/problemset/status/69/problem/E
func TestCF69E(t *testing.T) {
	testCases := [][2]string{
		{
			`5 3
1
2
2
3
3`,
			`1
3
2`,
		},
		{
			`6 4
3
3
3
4
4
2`,
			`4
Nothing
3`,
		},
		{
			`10 3
-55
-35
-80
91
-96
-93
-39
-77
4
29`,
			`-35
91
91
91
-39
-39
4
29`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, CF69E)
}
