// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/78/E 2300
// https://codeforces.com/problemset/status/78/problem/E?friends=on
func Test_cf78E(t *testing.T) {
	testCases := [][2]string{
		{
			`3 3
1YZ
1YY
100

0YZ
0YY
003`,
			`2`,
		},
		{
			`4 4
Y110
1Y1Z
1Y0Y
0100

Y001
0Y0Z
0Y0Y
0005`,
			`3`,
		},
		{
			`3 10
111
YZY
111

000
YZY
009`,
			`2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf78E)
}
