// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/97/C 2400
// https://codeforces.com/problemset/status/97/problem/C?friends=on
func Test_cf97C(t *testing.T) {
	testCases := [][2]string{
		{
			`3
0.115590 0.384031 0.443128 0.562356`,
			`0.4286122500`,
		},
		{
			`3
1 1 1 1`,
			`0.9999999999`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf97C)
}
