// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 提交地址：https://atcoder.jp/contests/abc221/submit?taskScreenName=abc221_e
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`3
1 2 1`,
			`3`,
		},
		{
			`3
1 2 2`,
			`4`,
		},
		{
			`3
3 2 1`,
			`0`,
		},
		{
			`10
198495780 28463047 859606611 212983738 946249513 789612890 782044670 700201033 367981604 302538501`,
			`830`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
// https://atcoder.jp/contests/abc221/tasks/abc221_e
