// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc141/tasks/abc141_f
// 提交：https://atcoder.jp/contests/abc141/submit?taskScreenName=abc141_f
// 对拍：https://atcoder.jp/contests/abc141/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc141_f&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc141/submissions?f.Status=AC&f.Task=abc141_f&orderBy=source_length
func Test_f(t *testing.T) {
	testCases := [][2]string{
		{
			`3
3 6 5`,
			`12`,
		},
		{
			`4
23 36 66 65`,
			`188`,
		},
		{
			`20
1008288677408720767 539403903321871999 1044301017184589821 215886900497862655 504277496111605629 972104334925272829 792625803473366909 972333547668684797 467386965442856573 755861732751878143 1151846447448561405 467257771752201853 683930041385277311 432010719984459389 319104378117934975 611451291444233983 647509226592964607 251832107792119421 827811265410084479 864032478037725181`,
			`2012721721873704572`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
