// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`[3,1]`, 
			`[-1,-1]`,
		},
		{
			`[5,3,1,2,5,1,2]`, 
			`[1,3]`,
		},
		{
			`[1,3,2,2,3,2,2,2,7]`, 
			`[3,3]`,
		},
		{
			`[2,3,3,2]`, 
			`[-1,-1]`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, nodesBetweenCriticalPoints, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-265/problems/find-the-minimum-and-maximum-number-of-nodes-between-critical-points/
