// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [b]")
	examples := [][]string{
		{
			`[4,9,3]`, `10`, 
			`3`,
		},
		{
			`[2,3,5]`, `10`, 
			`5`,
		},
		{
			`[60864,25176,27249,21296,20204]`, `56803`, 
			`11361`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, findBestValue, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/biweekly-contest-16/problems/sum-of-mutated-array-closest-to-target/
