// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc301/tasks/abc301_d
// 提交：https://atcoder.jp/contests/abc301/submit?taskScreenName=abc301_d
// 对拍：https://atcoder.jp/contests/abc301/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc301_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`?0?
2`,
			`1`,
		},
		{
			`101
4`,
			`-1`,
		},
		{
			`?0?
1000000000000000000`,
			`5`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
